import {
    useState
} from 'react'
import TCR from './img/answer/TCR.png';
import MHCClass2 from './img/answer/MHCClass2.png';
import IPEX from './img/answer/IPEX.png';
import CD28 from './img/answer/CD28.png';
import asthmaMechanism from './img/answer/asthmaMechanism.png';
import asthma from './img/answer/asthma.png';
import CTLA4 from './img/answer/CTLA4.png';
import Treg from './img/answer/Treg.png';
import TLRpattern from './img/answer/TLRpattern.png';
import TLR from './img/answer/TLR.png';
import ThDifferentiation from './img/answer/ThDifferentiation.png';
import Th17 from './img/answer/Th17.png';
import TcellGammaDelta from './img/answer/TcellGammaDelta.png';
import TcellEducation from './img/answer/TcellEducation.png';
import TcellDifferentiation from './img/answer/TcellDifferentiation.png';
import TcellActivationSignal from './img/answer/TcellActivationSignal.png';
import superantigen from './img/answer/superantigen.png';
import RLR from './img/answer/RLR.png';
import PerforinGranzyme from './img/answer/PerforinGranzyme.png';
import LPS from './img/answer/LPS.png';
import isotypeSwitch2 from './img/answer/isotypeSwitch2.png';
import isotypeSwitch1 from './img/answer/isotypeSwitch1.png';
import invariantChain from './img/answer/invariantChain.png';
import crossPresentation from './img/answer/crossPresentation.png';
import centralMemoryT from './img/answer/centralMemoryT.png';
import TCRSegments from './img/answer/TCRSegments.png';
import TI1antigen from './img/answer/TI1antigen.png';
import RSS from './img/answer/RSS.png';
import RAG from './img/answer/RAG.png';
import Nivolumab from './img/answer/Nivolumab.png';
import IL2 from './img/answer/IL2.png';
import IL1Beta from './img/answer/IL1Beta.png';
import epitope from './img/answer/epitope.png';
import CART from './img/answer/CART.png';
import BCellImmature from './img/answer/BCellImmature.png';
import antibodyGraph from './img/answer/antibodyGraph.png';
import AIRE from './img/answer/AIRE.png';
import receptorEditing from './img/answer/receptorEditing.png';
import tuberculosis from './img/answer/tuberculosis.png';
import TGFBeta from './img/answer/TGFBeta.png';
import NKCell from './img/answer/NKCell.png';
import MACInhibitor2 from './img/answer/MACInhibitor2.png';
import MACInhibitor1 from './img/answer/MACInhibitor1.png';
import IgE from './img/answer/IgE.png';
import HLATrophoblast from './img/answer/HLATrophoblast.png';
import diseaseFromHLA2 from './img/answer/diseaseFromHLA2.png';
import diseaseFromHLA1 from './img/answer/diseaseFromHLA1.png';
import antibodyProduce from './img/answer/antibodyProduce.png';
import antibodyFragmentation from './img/answer/antibodyFragmentation.png';
import TregTrophoblast from './img/answer/TregTrophoblast.png';
import Rh from './img/answer/Rh.png';
import MHCVariation from './img/answer/MHCVariation.png';
import MHCClass1 from './img/answer/MHCClass1.png';
import JAKSTAT from './img/answer/JAKSTAT.png';
import homing from './img/answer/homing.png';
import HIV from './img/answer/HIV.png';
import haplotype from './img/answer/haplotype.png';
import chemokinePosition from './img/answer/chemokinePosition.png';
import chemokine from './img/answer/chemokine.png';
import CD56bright from './img/answer/CD56bright.png';
import allergyIgE from './img/answer/allergyIgE.png';
import ABO from './img/answer/ABO.png';
import MICA from './img/answer/MICA.png';
import CD1 from './img/answer/CD1.png';
import PRR from './img/answer/PRR.png';
import preBCR from './img/answer/preBCR.png';
import complementPathway from './img/answer/complementPathway.png';
import C1INH from './img/answer/C1INH.png';
import anaphylaxis from './img/answer/anaphylaxis.png';
import TAM from './img/answer/TAM.png';
import immunorejection from './img/answer/immunorejection.png';
import GVHD from './img/answer/GVHD.png';
import TGFBetaIntestine from './img/answer/TGFBetaIntestine.png';
import retinoicAcid from './img/answer/retinoicAcid.png';
import oralTolerance from './img/answer/oralTolerance.png';
import opsonin from './img/answer/opsonin.png';
import NKCellReceptor from './img/answer/NKCellReceptor.png';
import mucosalImmunity from './img/answer/mucosalImmunity.png';
import MCell from './img/answer/MCell.png';
import HIVStructure from './img/answer/HIVStructure.png';
import dualAllergenExposureHypothesis from './img/answer/dualAllergenExposureHypothesis.png';
import question09082 from './img/question/question09082.png';
import question09081 from './img/question/question09081.png';











// import from './img/answer/.png'

export const useQuestionList = () => {
    const appName = 'anywhere-immunology'
    const jpName = '免疫学'
    const [questionList, setQuestionList] = useState([
        // ここに問題のリストを記述(選択式の場合は[0]に正解択をいれた配列をつくる)
        {
            groupTag: "2019TBL 選択問題",
            groupContents: [{
                    detailInfo: '',
                    questionImg: [],
                    questionSentence: 'ケモカインの作用について誤っているものを2つ選べ。',
                    choices: ['ケモカインは白血球を遊走させるサイトカインである', 'ケモカイン受容体の多くはリガンドが1つである', '好中球とマクロファージは共にCXCL8を介して炎症部位に遊走する', 'T細胞はCCR7を用いてリンパ節にホーミングする', '抗原を捕捉した樹状細胞はCCR7を用いて輸入リンパ管からリンパ節へ移行する', 'B細胞はCXCL13/CXCR5を用いてリンパ節濾胞領域へ移行する'],
                    answerImg: [chemokine, homing],
                    answer: '2と3が誤り',
                    commentary: '例えばCCR7 - CCL19/21など、ケモカイン受容体は様々なリガンドに結合して信号を伝達する。CXCL8(IL-8)は好中球の遊走因子で、マクロファージを遊走させるものではない。その他、CCR7は樹状細胞やT細胞をリンパ節の傍濾胞皮質（T細胞領域）へ誘導し、CXCR5はB細胞をリンパ節の濾胞（B細胞領域）へ誘導するなど、特定の白血球を特定の場所へ移動させるために様々なケモカインが活躍している。',
                },
                {
                    detailInfo: '',
                    questionImg: [],
                    questionSentence: '抗原提示分子について誤っているものを2つ選べ。',
                    choices: ['HLAクラスI分子はほぼ全ての有核細胞に発現している', ' 1細胞に発現するHLAクラスI分子は1種類だけである', '脂質は抗原提示されない', 'Major histocompatibility complex class 1 chain-related geneA (MICA)は抗原を提示しない', 'HLAには非同義置換が多い', 'インバリアント鎖はHLAクラスⅡ分子と会合し､内在性抗原ペプチドの結合を防ぐ'],
                    answerImg: [MHCVariation, CD1, MICA, MHCClass2],
                    answer: '2と3が誤り',
                    commentary: 'HLAはクラスⅠだけでA~Gあり、その中から複数がそれぞれの臓器（例えば胎盤ではEFGの3種類）で発現して、自己と非自己を区別している。例えばCD1dはガラクトシルセラミドなどの脂質をT細胞に抗原提示する。　その他、例えば核の無い赤血球にはHLAは発現しておらず、MICAはペプチド結合溝がへしゃげていてがん細胞や損傷している細胞に発現しNK細胞などに認識されるMHCクラスⅠ関連鎖遺伝子抗原で、HLAはアミノ酸配列が同じであっても、異なる対立遺伝子であることがある（非同義置換/ミスセンス変異）し、遺伝子が違っているインバリアント鎖(Ii)はHLAクラスⅡ分子がエンドソームで開裂されるまでHLAクラスⅡ分子と会合している。',
                },
                {
                    detailInfo: '',
                    questionImg: [],
                    questionSentence: 'PRR(pattern recognition receptor)とリガンドの組合せで誤っているものを2つ選べ。',
                    choices: ['TLR2 - Streptococcus pneumoniae(肺炎球菌)', 'TLR3 - Psudomonas aeruginosa(緑膿菌)', 'TLR5 - Escherichia coli(大腸菌)', 'TLR9 - Escherichia coli(大腸菌)', 'RIG-1 - Haemophilus influenzae(インフルエンザ菌)', 'NOD2 - Mycobacterium tuberculosis(結核菌)'],
                    answerImg: [PRR, TLR, TLRpattern],
                    answer: '2と5が誤り',
                    commentary: '肺炎球菌はグラム陽性の双球菌、緑膿菌や大腸菌や結核菌はグラム陰性桿菌、インフルエンザ菌はグラム陰性短桿菌。　→TLR3は二本鎖RNAを識別するので誤り。RLRは主にインフルエンザなどのRNAウイルスを識別するので、インフルエンザ菌は誤り。その他、大腸菌は鞭毛を持っているのでTLR5で識別される。NLRは細胞内寄生細菌を識別し、結核菌は細胞内寄生細菌であるので正しい（結核菌を識別するPRRとしてTLRやMincleなどのCLRも存在する）。感染や障害から我々の身体を防御するには、まず病原体やダメージを認識することが必要で、これらPRR（パターン認識レセプター）は炎症反応の引き金として非常に重要な役割を担っているといえる。',
                },
                {
                    detailInfo: '',
                    questionImg: [],
                    questionSentence: '胸腺におけるT細胞分化について誤っているものを2つ選べ。',
                    choices: ['・正の選択はCD4-CD8-T細胞で起こる', '正の選択とは自己抗原と適度に反応するT細胞を残すことである', '負の選択は胸腺皮質､正の選択は胸腺髄質でおこる', '核内タンパクAIRE(autoimmuneregulator)は種々の自己抗原を産生し､負の選択に寄与する', '胸腺プロテアソームはHLAクラス-I/Ⅱ分子に低親和性のペプチドを作ることで正の選択に寄与する', '正の選択の際にHLAクラスⅡ分子に提示されたペプチドを認識した細胞はCD4+T細胞へと分化する'],
                    answerImg: [TcellDifferentiation, AIRE, MHCClass1],
                    answer: '1と3が誤り',
                    commentary: 'T細胞はDNT細胞→DPT細胞→SPT細胞の順で成熟し、DP(CD4+CD8+)の段階で皮質で正の選択、SP(Single Positive)の段階で髄質でAIREなどによって負の選択が行われる。ユビキチン-プロテアソーム系で断片化されたペプチドが、CD8+T細胞にはHLAクラスⅠ分子、CD4+T細胞にはHLAクラスⅡ分子によって抗原提示される。T細胞の遺伝子再構成はこれら正の選択/負の選択より前の段階で、VDJセグメントを持つβ鎖から順番に行われる。',
                },
                {
                    detailInfo: '',
                    questionImg: [],
                    questionSentence: 'B細胞の骨髄での分化成熟に関わる分子として誤っているものを2つ選べ。',
                    choices: ['Activation-induced cytidine deaminase(AID)', 'Artemis', 'Bruton’s tyrosine kinase(BTK)', 'CD40', 'Recombination-activating gene-1/2(RAG)', 'Terminal deoxynucleotidyl transferase(TdT)'],
                    answerImg: [RAG, preBCR, isotypeSwitch1, isotypeSwitch2],
                    answer: '1と4が誤り',
                    commentary: 'B細胞はプロB細胞→プレB細胞→未熟B細胞→成熟B細胞の順に成熟し、まずH鎖、次いでL鎖(κ鎖→λ鎖)の順に遺伝子再構成が行われる。また、H鎖の再構成が終わりμH鎖が生成された段階で、μH鎖は代替L鎖・Igα・Igβと複合体：プレB細胞レセプター(pre-BCR)を形成し、プレB細胞となるため、H鎖遺伝子再構成はプロB細胞、L鎖遺伝子再構成はプレB細胞の段階で行われることとなる。　遺伝子再構成はV・D・Jセグメントそれぞれの間に存在するRSSを標的として、RAG1/2が切断した後Artemisによるヘアピン構造の分解、TdTによる変異に富んだ修復を行うことによって成立し、遺伝子再構成が成功した場合はpre-BCRから生存・細胞増殖シグナルが伝達される。ブルトン型チロシンキナーゼBTKはこの下流に存在し、この遺伝子が突然変異するとX連鎖無ガンマグロブリン血症(XLA)を発症する。 AID：シチジン脱アミノ化酵素やCD40はT-B相互作用やアイソタイプスイッチにかかわる分子で、成熟後の話。',
                },
                {
                    detailInfo: '',
                    questionImg: [],
                    questionSentence: 'アレルギー疾患と主要関連因子(抗体ならびにアレルギーの型)の組合せで誤っているものを2つ選べ。',
                    choices: ['尋麻疹 --- IgE(I型アレルギー）', '重症筋無力症 --- IgG(Ⅱ型アレルギー）', '全身性エリテマトーデス --- IgG(Ⅲ型アレルギー）', 'アレルギー性接触皮層炎 --- IgG(Ⅳ型アレルギー）', 'Basedow病(Graves病) --- IgG(V型アレルギー）', 'アナフィラキシー--- IgM(Ⅱ型アレルギー）'],
                    answerImg: [],
                    answer: 'アレルギー性皮膚接触炎、アナフィラキシー',
                    commentary: 'アナフィラキシーショックはⅠ型アレルギーが原因でIgEによるもの（蕁麻疹と同じ分類）。アレルギー性接触皮膚炎はⅣ型であるが、Ⅳ型は感作T細胞による過剰反応による遅延型過敏症で、抗体は直接関与しない。',
                },
                {
                    detailInfo: '',
                    questionImg: [],
                    questionSentence: '腫瘍免疫を抑制する因子と細胞の組合せについて誤っているものを2つ選べ。',
                    choices: ['CTLA-4 --- 樹状細胞', 'TGF-β --- M2マクロファージ', 'PD-L1 --- 腫瘍細胞', 'CD28 --- T細胞', 'PD-1 --- T細胞', 'TGF-β --- 制御性T細胞'],
                    answerImg: [CTLA4, TGFBeta, Nivolumab, CD28],
                    answer: '1と4が誤り',
                    commentary: '障害細胞は通常CD8+T細胞に認識され排除されるが、腫瘍は免疫チェックポイントなどによってこれを逃れている。CD28はT細胞の活性化に必須の共刺激因子であるため、CD28は腫瘍免疫を促進する因子である。一方で腫瘍細胞の発現するPD-L1はT細胞のPD-1と結合し腫瘍免疫を抑制してしまう。また、活性化(M2)マクロファージやTregから産生されるTGF-βもT細胞やマクロファージによる免疫反応を抑制してしまう。CTLA-4もCD8+T細胞やTregに発現して免疫反応を抑制する。',
                },
                {
                    detailInfo: '',
                    questionImg: [],
                    questionSentence: '補体について誤っているものを2つ選べ。',
                    choices: ['細菌に共有結合する', 'ヒト細胞に共有結合する', '活性化経路により補体作用が異なる', '肝臓で産生される易熱性タンパク質である', '補体が過剰に活性化されると補体抑制因子が産生される', 'C1-INHは補体因子以外の血漿中のセリンプロテアーゼにも作用する'],
                    answerImg: [anaphylaxis, complementPathway, C1INH],
                    answer: '2と3が誤り',
                    commentary: '補体(complement)とは主に肝臓で産生され血中に存在する易熱性タンパク質で、オプソニン作用・炎症作用の活性化・溶菌作用を行う。基本的に病原体に共有結合し活性を表すが、C3aとC5a(アナフィラトキシン)は病原体から遊離して肥満細胞と非共有結合し炎症作用の活性化を行う。病原体に結合したC3をC3→C3aとC3bに分解する酵素をC3転換酵素(C4b2a/C3bBb)という。補体活性化には第二経路・レクチン経路・古典経路の３つの経路があるが、経路の起点が異なる一方作用に関わる部分は共通していて、いずれも最終的にMACを形成して溶菌を行う。こういった補体活性は正常宿主細胞においてはC1-INH・CD59・DAF・I因子・Sタンパク質などの補体制御分子によって不活化されており、自己細胞が傷害されないようになっている。',
                },
                {
                    detailInfo: '',
                    questionImg: [],
                    questionSentence: '原発性免疫不全症候群とその特徴の組み合わせで誤っているものを2つ選べ。',
                    choices: ['Chediak-Higashi症候群 - リソソーム障害', 'DiGeroge症候群 - 低カルシウム血症', 'Wiskott-Aldrich症候群 - 血小板減少', 'X連鎖無ガンマグロブリン血症 - IL2RG遺伝子異常', '慢性肉芽腫症 - 活性酸素産生能欠損', '高IgE症候群 - 高頻度悪性腫瘍発生'],
                    answerImg: [preBCR],
                    answer: 'X連鎖無ガンマグロブリン血症、高IgE血症',
                    commentary: 'Chediak-Higashi 症候群はリソソーム輸送調節蛋白LYSTの変異により食胞（ファゴソーム）とリソソームの融合に障害がある、ペルオキシダーゼ陽性巨大顆粒が特徴的。リソソームに障害があるのは慢性肉芽腫症候群。　高頻度悪性腫瘍発生がみられるのはATMタンパクが欠損する毛細血管拡張性運動失調症(A-T)。IL-2Rγに変異がみられることがおおいのは、X-SCID（重症複合型免疫欠損症）。',
                },
                {
                    detailInfo: '',
                    questionImg: [],
                    questionSentence: '免疫組織化学染色(1-3)とフローサイトメトリー(4-6)について誤っているものを2つ選べ。',
                    choices: ['蛍光抗体法と酵素抗体法での染色結果は､いずれも光学顕微鏡で観察できる', '内因性ぺルオキシダーゼを多く含むものに赤血球と穎粒球がある', '間接法は直接法よりも検出感度が高い', '抗原の発現量と蛍光強度は相関しない', '転写因子などの細胞内タンパクの発現を検出することができる', '前方散乱光と側方散乱光からリンパ球と単球を区別することができる'],
                    answerImg: [],
                    answer: '1,4が誤り',
                    commentary: '蛍光抗体法では蛍光顕微鏡でないと観察できない。抗原の発現量が多いほど、蛍光強度は強くなる→免疫染色を利用すれば定量的に抗原発現量を調べることができる。　その他、FACSでは実習のような表面マーカーだけでなく核DNA量・細胞内抗原・酵素活性などについても、染色手順次第で調べることができる。リンパ球・単球・顆粒球は、FSCとSSCから区別することができる。',
                },
            ]
        },
        {
            groupTag: '2021本試験 選択問題',
            groupContents: [{
                    detailInfo: '',
                    questionImg: [],
                    questionSentence: '炎症の4徴候について、誤っているものを2つ選べ。',
                    choices: ['浮腫', '壊死', '発赤', '熱感', '疼痛', '腫脹'],
                    answerImg: [],
                    answer: '浮腫、壊死',
                    commentary: '機能不全も含めて5徴とする場合もある。',
                },
                {
                    detailInfo: '',
                    questionImg: [],
                    questionSentence: '原発性免疫不全症候群の特徴について、誤っているものを2つ選べ。',
                    choices: [
                        'Chediak-Higashi症候群 - 急性転化',
                        'Wiskott-Aidrich症候群 - 血小板減少',
                        'Digeorge症候群 - 低カルシウム血症',
                        'X連鎖無ガンマグロブリン血症 - ATM変異',
                        '慢性肉芽腫症 - ペルオキシダーゼ陽性巨大顆粒',
                        '毛細血管拡張性運動失調症 - 体幹失調',
                    ],
                    answerImg: [preBCR],
                    answer: '4と5が誤り',
                    commentary: 'プレB細胞では、遺伝子再構成が終わったばかりのH鎖と代替L鎖が発現して、pre-BCRを形成するが、この時BTK遺伝子が欠乏するとB細胞の成熟に障害が起こり、X連鎖無ガンマグロブリン血症を発症する。ATMの変異は毛細血管拡張性運動失調症（AT）にみられ、ペルオキシダーゼ陽性巨大顆粒はLYST遺伝子の異常などによりリソソーム輸送障害がおこる、Chediak-Higashi症候群の特徴。',
                },
                {
                    detailInfo: '',
                    questionImg: [],
                    questionSentence: 'PRRが認識するPAMPsと病原体の組み合わせについて、誤っているものを2つ選べ。',
                    choices: [
                        'TLR2 - リポポリサッカライド(LPS) - 大腸菌',
                        'TLR5 - フラジェリン - 大腸菌',
                        'TLR9 - ペプチドグリカン - 大腸菌',
                        'RIG-I  - RNAウイルス - インフルエンザウイルス',
                        'Dectin-1 - βグルカン - カンジダ',
                        'Mincle - トレハロースジミコール酸(TDM) - 結核菌',
                    ],
                    answerImg: [TLR, TLRpattern, PRR],
                    answer: '1と3が誤り',
                    commentary: 'TLR2はグラム陽性菌、TLR9は細菌DNAを主に認識する。大腸菌はグラム陰性桿菌で、鞭毛（フラジェリン）を持つ。Dection-1やMincleはCLRの一つで、真菌や結核菌を認識する。',
                },
                {
                    detailInfo: '',
                    questionImg: [],
                    questionSentence: 'T細胞の胸腺分化について、誤っているものを2つ選べ。',
                    choices: [
                        'γδT細胞の遺伝子再構成はαβT細胞の遺伝子再構成に先行する',
                        '正の選択の後に負の選択が起こる',
                        '正の選択は胸腺皮質で、負の選択は胸腺髄質で行われる。',
                        '正の選択の際にMHCクラスⅡ分子に提示されたペプチドを認識した細胞はCD8陽性T細胞へと分化する。',
                        '正の選択はダブルポジディブ期に起こる',
                        'AIRE(Autoimmune regulator)は隔絶抗原を発現することで負の選択に関与している。',
                    ],
                    answerImg: [TcellDifferentiation, AIRE],
                    answer: '4と6が誤り',
                    commentary: 'MHC class2を認識 → CD4+T細胞、AIREはゲノムにコードされた自己抗原を無差別発現する。T細胞はDNT細胞→DPT細胞→SPT細胞→成熟T細胞の順に成熟し、その間に遺伝子再構成(β鎖→α鎖)・皮質での正の選択・髄質での負の選択が行われる。',
                },
                {
                    detailInfo: '',
                    questionImg: [],
                    questionSentence: '免疫組織化学染色について、誤っているものを2つ選べ。',
                    choices: [' 酵素抗体染色は光学顕微鏡で観察できる。', '酵素抗体染色は永久標本が作れる。 ', '直接法は間接法より感度が高い。 ', '脱パラフィンにはキシレンが頻用される。 ', '内因性ペルオキシダーゼは赤血球や顆粒球に存在する。 ', '内因性ペルオキシダーゼの不活化にはエタノールを用いる。'],
                    answerImg: [],
                    answer: '3と6が誤り',
                    commentary: '直接法では一次抗体に直接酵素（ペルオキシダーゼ）が付加されているため、間接法ではできるような増感（少量の抗原に対して発色が強くなるように感度を調節すること）を行うことができない。内因性ペルオキシダーゼは免疫染色の際に使われる基質（DABなど）を酸化して発色させる、赤血球や顆粒球に存在する酵素で、実習では予め失活されていた。このような内在性オキシダーゼの不活化には、今回の実習ではメタノール（CD8)や過酸化水素（PD-L1）が用いられた。',
                },
                {
                    detailInfo: '',
                    questionImg: [],
                    questionSentence: '移植免疫について、誤っているものを2つ選べ。',
                    choices: ['HLA 一致の兄弟間では拒絶反応は起こらない。', ' 超急性拒絶は主に既存抗原が補体依存性に内皮傷害を生じることで起こる。 ', '急性拒絶は主にT細胞によるものである。 ', '慢性拒絶の病理学的特徴は血管肥厚による閉塞と線維化である。 ', '急性 GVHD の主な対象臓器は皮膚、肝臓、消化器である。 ', '急性 GVHD はレシピエントの T細胞が移植片に対して拒絶反応を示すことで起きる'],
                    answerImg: [immunorejection, GVHD],
                    answer: '1と6が誤り ',
                    commentary: '臓器移植の際には拒絶反応が出る場合がある。超急性拒絶は24時間以内の拒絶反応で、急性拒絶は7日〜100日程度後、慢性拒絶は100日以降に起こる移植後拒絶反応である。超急性拒絶では補体の活性化などによる血管内皮への障害・炎症による血栓が生じる。急性拒絶では移植組織の樹状細胞が移植片をT細胞に直接抗原提示してしまうことによって起こる。一方で慢性拒絶では移植組織のMHC分子を異物として抗原提示する、間接抗原提示が原因で起こると言われている。慢性拒絶では炎症により血管の平滑筋細胞が増大し血管壁が閉塞する特徴がある。繊維化も見られる。→4は正しい。臓器移植前にHLAの一致は必ず確認するが、術後こういった拒絶反応は現在でも珍しくないのはHLA以外の要素（例えばminor HLAなど）が原因で非自己と認識されてしまうからだと言われている。白血病などの際に行われる造血幹細胞の移植では、移植片にも（ドナー由来の）T細胞が含まれるためさらに予後が悪く、移植片に含まれるドナーT細胞が宿主の正常細胞に発現する組織適合抗原を異物と認識して、GVHDという拒絶反応を引き起こすが、このうち急性GVHDは主に皮膚・肝臓・消化管の上皮細胞を標的として、慢性GVHDは多臓器を標的として起こるという特徴がある。',
                },
                {
                    detailInfo: '',
                    questionImg: [],
                    questionSentence: '自己免疫疾患について、誤っているものを2つ選べ。',
                    choices: ['自己免疫疾患は微生物感染によって引き起こされうる。 ', 'Basedow 病は、甲状腺ホルモンに自己抗体が作られることによるⅤ型アレルギーである。 ', 'Ⅰ型糖尿病は、膵β細胞に対する CD8陽性T細胞が強く関与している。  ', '強直性脊椎炎は HLA-B27 の多型によるもので、女性に多い。 ', '多発性筋炎/皮膚筋炎では自己抗体である抗 Jo-1 抗体の上昇を認める。 ', '関節リウマチの診断で、リウマチ因子(Rheumatoid Factor)は抗 CCP 抗体よりも特異性が低い。 '],
                    answer: '2と4が誤り',
                    commentary: 'Basedow病は甲状腺刺激ホルモン（TSH）受容体に対する自己抗体が産生され、甲状腺ホルモンの分泌が亢進される自己免疫疾患（5型アレルギー）。強直性脊椎炎はHLA-B27の多型に患者が多く、男性のほうが多い点で珍しい（そして試験に出やすい）自己免疫疾患。エストロゲンがTregやTh17の因子やAIREの発現に関与しているため、多くの自己免疫疾患は女性に多い。',
                    answerImg: [],
                },
                {
                    detailInfo: '',
                    questionImg: [],
                    questionSentence: '免疫寛容について、誤っているものを2つ選べ。',
                    choices: ['中枢性寛容と末梢性寛容は相互補完的に働くため、一方の破綻だけでは自己免疫疾患を発症しない。 ', '通常、食物抗原に対しては経口寛容が成立しているため、免疫応答は起こらない。 ', '制御性T細胞 (Treg) は CTLA-4 を高発現しており、CD28 と CD80/CD86 の結合を競合的に阻害することで T細胞の活性化を抑制する。 ', 'Treg は IL-2 Rα鎖(CD25) を発現しているため、 ナイーブT細胞よりIL-2に対する反応性が高い。 ', 'Treg は IL-10、TGF-βなど抑制性サイトカインを産生し、T細胞の活性化を抑制する。', 'IPEX 症候群は、Treg の分化に必須の転写因子 T-bet の遺伝子異常により発症する。'],
                    answerImg: [Treg, TGFBeta],
                    answer: '1と6が誤り',
                    commentary: '中枢・末梢どちらの免疫寛容が破綻しても自己免疫疾患の原因となるIPEX症候群に関わる、Treg の分化に必須の遺伝子はFoxp3。CTLA-4とCD80/86はいずれもナイーブT細胞のCD28のリガンド。Tregは他にT細胞の分化に必須のIL-2を回収したり、TGF-βなどを産生したりすることによって免疫反応を抑制する。',
                },
                {
                    detailInfo: '',
                    questionImg: [],
                    questionSentence: '腫瘍免疫について、誤っているものを2つ選べ。',
                    choices: ['がん細胞ではMHCに変異が蓄積しており、免疫系によって自己と認識されない', '免疫チェックポイント阻害薬は正の選択と負の選択の調整を行う', '腫瘍細胞はPD-L1を発現し免疫監視からの逃避機構を獲得している', 'CAR-T療法の標的は固形腫瘍である'],
                    answerImg: [Nivolumab, CART],
                    answer: '2と4が誤り',
                    commentary: 'ミスマッチ修復機構の欠損などが原因で変異を繰り返したがん細胞はもはや自己の細胞とは認識されなくなっており、リンパ球が浸潤していることが多いが、多くのがん細胞はPD-L1(免疫チェックポイント機構)を発現することでT細胞による排除から逃れている。このPD-L1はT細胞上のPD-1に対するリガンドであり正の選択や負の選択（T細胞のセレクション）とは無関係である。CAR-T療法は患者のT細胞にCAR遺伝子を導入し患者に戻すがん治療法であるが、固形がんにはハードルが高い。主な対象は白血病などの血球系がん→薬品名：キムリア。',
                },
                {
                    detailInfo: '',
                    questionImg: [],
                    questionSentence: 'サイトカインについて、誤っているものを2つ選べ。',
                    choices: ['IL-1β前駆体はプロテアソームによって切断され成熟する。', 'IL-2 は T細胞、NK細胞の分化を促進するが B細胞の活性化は抑制する。', 'IL-12 は IFN-γの産生を促し Th1細胞の分化を促進する。', 'IL-15 は NK細胞を分化、増殖させる。 ', 'IL-17 過剰分泌は上皮細胞を増殖させ、尋常性乾癬を引き起こす。 ', 'IL-33 は内皮細胞の傷害によって産生され、自然リンパ球 ILC2 の分化を促進する。 '],
                    answer: '2と6が誤り',
                    answerImg: [IL1Beta, IL2, ThDifferentiation],
                    commentary: 'IL-1βの成熟には（TLRなどの刺激→）前駆体の生成と、（NLRの活性化→）ICE:IL-1β converting enzymeによる前駆体の切断が必要。IL-2はB細胞の活性化にも働く。尋常性乾癬はHLA多型との関連も認められている。',
                },
                {
                    detailInfo: '',
                    questionImg: [],
                    questionSentence: '遺伝子再構成について、誤っているものを2つ選べ。',
                    choices: ['12塩基と 23塩基の配列が近接した RSS を RAG-1/2が認識して切断する。 ', 'TdTはプロ細胞期に発現するため、L鎖よりも H鎖の方が接合部多様性が高い。', 'L 鎖ではκ鎖とλ鎖の遺伝子再構成が同時に起こる。 ', ' 遺伝子再構成は骨髄において行われ、多様性を獲得する。 ', '接合部多様性は主に CDR3 の領域に存在する。 ', 'レセプター編集とは、CRISPR/Cas9 により L鎖遺伝子が再構成されることである。 '],
                    answerImg: [RSS, RAG, BCellImmature, receptorEditing],
                    answer: '3と6が誤り',
                    commentary: 'RSS(Recombination Signal Sequence/組み換え認識配列)はVセグメント・Dセグメント・Jセグメントの間にある数十bpの配列で、遺伝子再構成の際の切り出し部分のターゲットとなっている。切り出しにはRAG-1,2(Recombination Activating Gene/VDJ組み換え酵素)によって引き起こされ、切られたDNA末端はArtemisやTdT(Terminal Deoxynucleotidyl Transferase/末端ヌクレオチド付加酵素)によって変異に富む修復を受ける。B細胞の遺伝子再構成は骨髄で行われる。遺伝子再構成はH鎖遺伝子→L鎖遺伝子(κ→λ)の順に行われるが、遺伝子再構成がうまくいかなかった場合はL鎖遺伝子で新たな遺伝子再構成が行われる→レセプター編集:Receptor Editing',
                },

                {
                    detailInfo: '',
                    questionImg: [],
                    questionSentence: '抗体について、誤っているものを2つ選べ。',
                    choices: ['抗体は血清タンパク質を電気泳動したときのγグロブリン分画に存在する。 ', '膜型の IgM と IgD は単一の成熟B細胞で同時に発現する。 ', '抗体をペプシン分解すると 2つのFabと1つのFcに分かれる。 ', '成熟した B細胞は膜型抗体と分泌型抗体をつくる。 ', 'IgM は 5量体であるので、抗原と結合する部位は 10 箇所ある。 ', '血清中の IgGが最も多いのは、IgGが自然抗体として産生されるからである。'],
                    answerImg: [antibodyFragmentation, antibodyProduce],
                    answer: '3と6が誤り',
                    commentary: '抗体はペプシンで分解されると1個のF(ab’)2とペプチド断片に分解される。パパインで分解されると2個のFabと1このFcに分解される。B細胞は感染していなくても常時IgM（膜型＆分泌型）とIgDを産生していて（自然抗体）、クラススイッチを行うことでIgGを分泌するようになる。→IgGは自然抗体ではない。',
                },
                {
                    detailInfo: '',
                    questionImg: [],
                    questionSentence: '粘膜免疫について、誤っているものを2つ選べ。',
                    choices: ['M細胞は抗原を貪食し、パイエル板を介して T細胞に抗原を提示する。 ', 'リンパ球はレチノイン酸によって粘膜固有層にホーミングされる。', '樹状細胞の産生するTGF-βにより制御性T細胞とTh17細胞が生じる', ' 粘膜で抗原の免疫寛容を誘導すれば、全身性の免疫寛容をもたらす。 ', '経口免疫の方が、経皮免疫より免疫寛容を誘導しやすい。 ', '免疫寛容を獲得した人の血清を別の人に注射した場合、免疫寛容が誘導される。 '],
                    answerImg: [MCell, retinoicAcid, TGFBetaIntestine, mucosalImmunity, dualAllergenExposureHypothesis, oralTolerance],
                    answer: '1と6が誤り',
                    commentary: 'M細胞は抗原を直接樹状細胞に流す。その他、上皮細胞がFcRnを介してオプソニン化された抗原を樹状細胞に渡したり、樹状細胞が樹状突起を伸ばして抗原を取り込んだりもする。腸管の樹状細胞はビタミンAをレチノイン酸に変換する酵素を発現し、レチノイン酸に活性化中のT細胞やB細胞が曝露されると、ケモカイン受容体CCR9やインテグリンα4β7を発現させることで、粘膜固有層選択的ホーミングに寄与する。腸管では経口免疫寛容のためTregやTh17細胞が活動している。粘膜を使った免疫獲得・免疫寛容の誘導は粘膜ワクチンなどに利用されている。経口免疫寛容は制御性T細胞の役割であるため、Tregを別の人に注射すれば免疫寛容が誘導されるが、血清には含まれていない。',
                },
                {
                    detailInfo: '',
                    questionImg: [],
                    questionSentence: '膜侵襲複合体(MAC)の形成を直接抑制する分子を2つ選べ。',
                    choices: ['B因子', 'CD59', 'CD46', 'H因子', 'I因子', 'Sタンパク質'],
                    answerImg: [MACInhibitor1, MACInhibitor2],
                    answer: 'CD59、Sタンパク質',
                    commentary: 'MAC（膜侵襲複合体）は補体活性化経路の最終段階に生成される。I因子やH因子は補体C3の消費をコントロールする補体制御因子で、B因子は第二経路の中間産物C3b→C3bBに必須。CD46は正常細胞の補体制御分子として補体活性化を抑制する。その他、C3a-INT、TAFI、ClusterinがMACの形成を直接阻害する。',
                },
                {
                    detailInfo: '',
                    questionImg: [],
                    questionSentence: 'HLAに関連した疾患で、オッズ比が1000以上のものをを2つ選べ。',
                    choices: ['Ⅰ型糖尿病', '潰瘍性大腸炎', 'ナルコレプシー', '関節リウマチ', '強直性脊椎炎', 'Behçet病'],
                    answerImg: [diseaseFromHLA1, diseaseFromHLA2],
                    commentary: 'HLAは自己と非自己を区別する抗原で、HLAが異なると提示できるペプチドが異なるため、特定の疾患は特定のHLA多型で顕著に見られる（→オッズ比が高い）ことがある。特に日本人では強直性脊椎炎・ナルコレプシー・インスリン自己免疫症候群でオッズ比が1000を超えており、HLAと疾患感受性・疾患抵抗性が強く関連している。その他、Ⅰ型糖尿病・関節リウマチ・尋常性乾癬・Behcet病もHLA多型との関連が認められる（オッズ比は比較的高くない）',
                    answer: 'ナルコレプシー・強直性脊椎炎',
                },
                // {
                //     detailInfo: '',
                //     questionImg: [],
                //     questionSentence: '抗原提示について、誤っているものを2つ選べ。',
                //     choices: ['', '', '', '', '', ''],
                //     answerImg: [],
                //     answer: '',
                //     commentary: '',
                // },
                {
                    detailInfo: '',
                    questionImg: [],
                    questionSentence: '生殖免疫について、誤っているものを2つ選べ。',
                    choices: ['HLA-Eは NKレセプターCD94/NKG2C で NK細胞を活性化させ、サイトカイン放出を促進する。 ', 'NK細胞は一つの細胞上に KARと KIRを持つ。 ', '胎盤トロホブラストには CD55 があり、父由来 HLAに対する遮断抗体として働く。 ', '妊娠初期には M1マクロファージは M2マクロファージより多い ', '胎盤脱落膜上には制御性T細胞が増加し、胎児の父系抗原特異的な反応を制御している。 ', '脱落膜 NK細胞のほとんどは CD56弱陽性NK細胞である。 '],
                    answerImg: [HLATrophoblast, NKCell],
                    answer: '4と6が誤り',
                    commentary: '胎盤血液関門での免疫寛容にはHLAやNK細胞、制御性T細胞などが関与している。胎盤トロホブラストでは多型性に乏しいHLA-E/F/Gが発現していて、脱落膜白血球の70%を占めるNK細胞からの攻撃を避けている。また脱落膜NK細胞の80%はCD56 bright NK細胞であり、細胞障害というよりはサイトカイン産生を主におこなっている。脱落膜白血球のうち20%を占めるマクロファージのうち、M1マクロファージとM2マクロファージは同程度存在する。NK細胞はKARとKIA両方持ち、これらの組み合わせでがん細胞を認識している。',
                },
                {
                    detailInfo: '',
                    questionImg: [],
                    questionSentence: '感染症について、誤っているものを2つ選べ。',
                    choices: ['肺炎球菌やインフルエンザ菌など、莢膜を持つ細菌の貪食にはオプソニン化が重要である。', '結核診断には結核特異的な抗体の抗体価を測定するのが有効である。 ', ' 結核性胸膜炎において、胸水中の ADA活性上昇が認められる。 ', '寄生虫 (蠕虫) 感染では好酸球増加と IgE上昇が起こる。 ', ' HIV感染症で、CD4陽性T細胞数が 200/mm³を下回ると日和見感染症、腫瘍などの AIDS 指標疾患を発症しやすくなる。 ', 'SARS-CoV-2 は気道の上皮細胞に感染し、他の上皮細胞には感染しない。 '],
                    answerImg: [opsonin, antibodyProduce, tuberculosis, IgE],
                    answer: '2と6が誤り',
                    commentary: '莢膜は貪食細胞に認識されにくいが、補体や抗体によるオプソニン化を受けると貪食されるようになる。結核診断には抗体価ではなくIFN-γ濃度を調べる→ツベルクリン検査。新型コロナは腸管にも感染する。',
                },
                // {
                //   detailInfo: '',
                //   questionImg: [],
                //   questionSentence: 'について、誤っているものを2つ選べ。',
                //   choices: ['', '', '', '', '', ''],
                //   answerImg: [],
                //   answer: '',
                //   commentary: '',
                // },
                // {
                //     detailInfo: '',
                //     questionImg: [],
                //     questionSentence: 'について、誤っているものを2つ選べ。',
                //     choices: ['', '', '', '', '', ''],
                //     answerImg: [],
                //     answer: '',
                //     commentary: '',
                // },
                // {
                //   detailInfo: '',
                //   questionImg: [],
                //   questionSentence: 'について、誤っているものを2つ選べ。',
                //   choices: ['', '', '', '', '', ''],
                //   answerImg: [],
                //   answer: '',
                //   commentary: '',
                // },
                // {
                //     detailInfo: '',
                //     questionImg: [],
                //     questionSentence: 'について、誤っているものを2つ選べ。',
                //     choices: ['', '', '', '', '', ''],
                //     answerImg: [],
                //     answer: '',
                //     commentary: '',
                // },
                // {
                //   detailInfo: '',
                //   questionImg: [],
                //   questionSentence: 'について、誤っているものを2つ選べ。',
                //   choices: ['', '', '', '', '', ''],
                //   answerImg: [],
                //   answer: '',
                //   commentary: '',
                // },
                // {
                //     detailInfo: '',
                //     questionImg: [],
                //     questionSentence: 'について、誤っているものを2つ選べ。',
                //     choices: ['', '', '', '', '', ''],
                //     answerImg: [],
                //     answer: '',
                //     commentary: '',
                // },
                // {
                //   detailInfo: '',
                //   questionImg: [],
                //   questionSentence: 'について、誤っているものを2つ選べ。',
                //   choices: ['', '', '', '', '', ''],
                //   answerImg: [],
                //   answer: '',
                //   commentary: '',
                // },
                // {
                //     detailInfo: '',
                //     questionImg: [],
                //     questionSentence: 'について、誤っているものを2つ選べ。',
                //     choices: ['', '', '', '', '', ''],
                //     answerImg: [],
                //     answer: '',
                //     commentary: '',
                // },
                // {
                //   detailInfo: '',
                //   questionImg: [],
                //   questionSentence: 'について、誤っているものを2つ選べ。',
                //   choices: ['', '', '', '', '', ''],
                //   answerImg: [],
                //   answer: '',
                //   commentary: '',
                // },
                // {
                //     detailInfo: '',
                //     questionImg: [],
                //     questionSentence: 'について、誤っているものを2つ選べ。',
                //     choices: ['', '', '', '', '', ''],
                //     answerImg: [],
                //     answer: '',
                //     commentary: '',
                // },
                // {
                //   detailInfo: '',
                //   questionImg: [],
                //   questionSentence: 'について、誤っているものを2つ選べ。',
                //   choices: ['', '', '', '', '', ''],
                //   answerImg: [],
                //   answer: '',
                //   commentary: '',
                // },
                // {
                //     detailInfo: '',
                //     questionImg: [],
                //     questionSentence: 'について、誤っているものを2つ選べ。',
                //     choices: ['', '', '', '', '', ''],
                //     answerImg: [],
                //     answer: '',
                //     commentary: '',
                // },
                // {
                //   detailInfo: '',
                //   questionImg: [],
                //   questionSentence: 'について、誤っているものを2つ選べ。',
                //   choices: ['', '', '', '', '', ''],
                //   answerImg: [],
                //   answer: '',
                //   commentary: '',
                // },

                // {
                //   detailInfo: '',
                //   questionImg: [],
                //   questionSentence: 'について、誤っているものを2つ選べ。',
                //   choices: ['', '', '', '', '', ''],
                //   answerImg: [],
                //   answer: '',
                //   commentary: '',
                // },
                // {
                //   detailInfo: '',
                //   questionImg: [],
                //   questionSentence: 'について、誤っているものを2つ選べ。',
                //   choices: ['', '', '', '', '', ''],
                //   answerImg: [],
                //   answer: '',
                //   commentary: '',
                // },
            ],
        }, {
            groupTag: "2022本試験 選択問題",
            groupContents: [{
                    detailInfo: '',
                    questionImg: [],
                    questionSentence: '気管支喘息の特徴はどれか',
                    choices: ['気管支平滑筋の増生', ' 粘液の分泌低下', 'IL-5 による好中球増多', 'IL-12 による自然リンパ球増多'],
                    answerImg: [asthma, asthmaMechanism],
                    answer: '気管支平滑筋の増生',
                    commentary: '粘膜は貯留が見られるほど分泌亢進され、アレルギーなのでIL-5による好酸球増多もみられる。獲得免疫であるTh2がIL-4により増多している（IL-12はTh1で、細胞内細菌/結核やウイルスに対応する）。',
                },
                {
                    detailInfo: '',
                    questionImg: [],
                    questionSentence: '免疫グロブリン(IgG)の抗原認識部位を構成するものは？',
                    choices: ['H鎖の3つの超可変ループ', 'L 鎖の3つの超可変ループ', '6つの超可変ループ：H鎖とL鎖のそれぞれ3つの超可変ループが一つずつ', '6つの超可変ループ：H鎖の3つの超可変ループが二つ', '12個の超可変ループ：H鎖とL鎖それぞれ3つの超可変ループが二つずつ'],
                    answerImg: [epitope],
                    answer: '6つの超可変ループ：H鎖とL鎖のそれぞれ3つの超可変ループが一つずつ',
                    commentary: 'Igドメインは2層のβシートによる球状の構造をしていて、抗体それぞれで配列が異なっている → 超可変領域:hypervariable regionとよばれる。超可変領域はH鎖とL鎖ともに3つ存在する。',
                },
                {
                    detailInfo: '',
                    questionImg: [],
                    questionSentence: 'T細胞非依存性抗原によって産生される免疫グロブリンのタイプは？ ',
                    choices: ['IgE', 'IgD', 'IgM', 'IgA', 'IgG'],
                    answerImg: [TI1antigen],
                    answer: 'IgM',
                    commentary: 'タンパク抗原に対する抗体産生応答には、抗原特異的なTh細胞による補助が必要であるが、TLRのリガンドとなる部分を持つような抗原：TI-1抗原（LPS・DNA・RNA）や細菌細胞壁の多糖のようなきわめて反復性の高い構造：TI-2抗原（細菌莢膜・多糖類）などはT細胞非依存性抗原で、B細胞を直接活性化させ、主にIgMを産生する。（一部IgGを産生する場合もある）',
                },
                {
                    detailInfo: '',
                    questionImg: [],
                    questionSentence: '新型コロナワクチンの追加接種の 3 週間後にどのサブクラスが増加しているか。',
                    choices: ['IgA', 'IgD', 'IgE', 'IgG', 'IgM'],
                    answerImg: [antibodyGraph],
                    answer: 'IgG',
                    commentary: '即時にIgMが産生されるが、時間とともにIgGが増えていく',
                },
                {
                    detailInfo: '',
                    questionImg: [],
                    questionSentence: '新しく産生された MHC クラスⅡに内在性ペプチドが結合することを防ぐものをすべて選べ。',
                    choices: ['インバリアント鎖', 'CLIP', 'HLA-DM'],
                    answerImg: [MHCClass2],
                    answer: 'インバリアント鎖、CLIP',
                    commentary: 'インバリアント鎖（Ii:Invariant chain）は小胞体内において、小胞体内にあるペプチドがHLA ClassⅡ分子に結合することを防いでいる。Iiはエンドソームで開裂され、CLIP部分だけがクラスⅡ分子上に残り、不適格なペプチドの結合を防いでいる。HLA-DMはCLIPをクラスⅡ分子から外し、抗原ペプチドと入れ替える。',
                },
                {
                    detailInfo: '',
                    questionImg: [],
                    questionSentence: 'MHC クラスⅠの提示経路で、タンパク質分解処理のために結合する分子はどれか。',
                    choices: ['カルネティキュリン', 'ペプシン', 'タパシン', 'ユビキチン', 'カルネキシリン'],
                    answerImg: [MHCClass1],
                    answer: 'ユビキチン',
                    commentary: 'ユビキチン-プロテアソーム系で内在性抗原をペプチド断片に変えて、HLA class1分子に会合する。MHC Class2分子による提示経路では、ファゴサイトーシスで断片化を行う',
                },
                {
                    detailInfo: '',
                    questionImg: [],
                    questionSentence: '次のうち、T細胞が発現していないものを選べ',
                    choices: ['CD3', 'CD4', 'CD8', 'CD28', 'CD86'],
                    answerImg: [TCR, CD28],
                    answer: 'CD86',
                    commentary: 'CD3はT細胞の受容体複合体の一部として、CD28はT細胞活性化の補助因子レセプターとしてはたらく。CD80とCD86はCD28のリガンドとして抗原提示細胞で機能し、Tregの制御機構に利用される。',
                },
                {
                    detailInfo: '',
                    questionImg: [],
                    questionSentence: 'シグナル伝達の時の生化学的反応を選べ',
                    choices: ['グリコシル化', 'チロシンリン酸化', 'ユビキチン化', 'アセチル化', 'メチル化'],
                    answerImg: [JAKSTAT],
                    answer: 'チロシンリン酸化',
                    commentary: '主なサイトカインによる信号を伝達するJAK-STAT経路では、次々とチロシン残基がリン酸化され、最終的に核内で標的遺伝子の転写を誘導する。',
                },
                {
                    detailInfo: '',
                    questionImg: [],
                    questionSentence: 'ナイーブT細胞が二次リンパ組織へ遊走するときに必要な分子を選べ',
                    choices: ['CCR7 - CCL21', 'CXCR3 - CCR3', 'CXCR4 - CXCL12', 'CXCR5 - CXCL19', "CCR10 - Lセレクチン"],
                    answerImg: [chemokine, homing, chemokinePosition],
                    answer: 'CCR7-CCL19/21',
                    commentary: 'Naive T cellや樹状細胞にはCCR7が発現していて、二次リンパ組織（リンパ節）への遊走にはHEVに局在するCCL19/21が必須。その他、B細胞の二次リンパ組織への遊走にはCXCR5-CXCL13、骨髄への遊走にはCXCR4-CXCL12が関与する。他の選択肢はレセプター-リガンドの関係にない。',
                },
                {
                    detailInfo: '',
                    questionImg: [],
                    questionSentence: 'HIVが侵入する際に直接関係しないのは？',
                    choices: ['CD4', 'MHCクラス1', 'CCR5', 'CXCR4', 'エンベロープ'],
                    answerImg: [HIV, HIVStructure],
                    answer: 'MHCクラス1',
                    commentary: 'HIVはCD4+T細胞に感染するために、CD4を認識する糖蛋白gp120とケモカインレセプター（共刺激因子）CCR5やCXCR4と結合する糖蛋白gp41を発現している。腸管で感染するウイルスとは異なりHIVはエンベロープを持つ。MHCクラス1分子はCD4+T細胞と直接関係しない',
                },
                {
                    detailInfo: '',
                    questionImg: [],
                    questionSentence: '1ワクチンで撲滅したウイルスは？',
                    choices: ['ポリオ', '風疹', '結核', '天然痘', '破傷風'],
                    answerImg: [],
                    answer: '天然痘',
                    commentary: '1958年に年間1000万人がなくなっていたが、種痘ワクチンが著効し1980年根絶が宣言された。天然痘（痘瘡）は人以外に自然宿主を持たず、不顕性感染が無く、患者の識別が容易で、伝播力が比較的小さく、極めて有効なワクチンがあったなどの理由が重なり、撲滅できたといわれている。',
                },
                {
                    detailInfo: '',
                    questionImg: [],
                    questionSentence: 'T細胞の機能不全と関係のない疾患は？',
                    choices: ['がん', 'ウイルス感染', '自己免疫疾患', '結核菌感染', '黄色ブドウ球菌感染'],
                    answerImg: [ThDifferentiation, Nivolumab],
                    answer: '結核菌感染',
                    commentary: 'Th1はウイルスや細胞内細菌に反応し、特に結核菌に感染した場合はIFN-γを産生し、マクロファージなどを刺激する。しかしながらマクロファージは結核菌を死滅させることができず、ラングハンス巨細胞や類上皮細胞へ変化し肉芽腫が形成される。→T細胞由来のIFN-γは診断（ツベルクリン検査）には有用であるが感染防御には寄与していないと考えられる。その他、CD8+T細胞はがん細胞を認識し、Th17の自己抗原への誤認識により自己免疫疾患（関節リウマチなど）が起こると言われていて、黄色ブドウ球菌などの細胞外細菌に対してもT細胞は活動する。黄色ブドウ球菌はスーパー抗原によってT細胞のサイトカイン産生をかく乱することも知られている。',
                },

                {
                    detailInfo: '',
                    questionImg: [],
                    questionSentence: 'どのレシピエントにも輸血が可能なドナーの血液型とは？',
                    choices: ['A型', 'B型', 'AB型', 'O型', 'Rh+型'],
                    answerImg: [ABO, Rh],
                    answer: 'O型',
                    commentary: '血液型はA、Bの抗原を赤血球が保有しているかどうかをあらわすので、O型の場合はA抗原・B抗原どちらも持っていないため輸血した赤血球が抗原抗体反応を引き起こすことがない。ただし血中に抗A抗体、抗B抗体は保有しているので注意。Rh+の赤血球はRh抗原を持っているため、Rh-の人に輸血すると抗原抗体反応をしてしまう。Rh抗体はIgGであり胎盤を通過してしまうため、新生児溶血性疾患の原因となる。クームス試験によって調べることができる。',
                },
                // {
                //     detailInfo: '',
                //     questionImg: [],
                //     questionSentence: '腎移植した血小板の抗原の抗体を持っている場合における拒絶反応についての問い',
                //     choices: ['数分でヤバイ', '数時間でヤバイ', '数日でヤバイ', '日和見何たら', ''],
                //     answerImg: [],
                //     answer: '',
                //     commentary: '',
                // },
                {
                    detailInfo: '',
                    questionImg: [],
                    questionSentence: '二回目の妊娠、母親はO型Rh-、父親はO型Rh+、胎児が陥る可能性のある疾患',
                    choices: ['Ⅰ型アレルギー早期', 'Ⅰ型アレルギー後期', 'Ⅱ型アレルギー', 'Ⅲ型アレルギー', 'Ⅳ型アレルギー'],
                    answerImg: [Rh],
                    answer: 'Ⅱ型アレルギー',
                    commentary: '新生児溶血性疾患。Rh+の胎児赤血球に対してRh-の母親がIgG抗体を産生してしまうことにより、胎児赤血球が破壊される。検査にはクームス試験が利用される。抗体反応によって赤血球が破壊されるため、Ⅱ型アレルギーに分類される。ABO血液型に対する抗体はIgMであるため胎盤を通過しない。Ⅱ型アレルギーは抗体による細胞障害によって引き起こされ、Ⅲ型アレルギーは抗原交代複合体の沈着によって引き起こされる。Ⅴ型アレルギーはⅡ型に類似していて、抗体によって特定の細胞が増殖され起こる',
                },
                {
                    detailInfo: '',
                    questionImg: [],
                    questionSentence: '13歳の男児が蜂に刺され、数分後にショック状態となった。この説明として正しいのはどれか？',
                    choices: ['毒素抗原によるクラススイッチ', '毒素抗原による補体活性化', 'マスト細胞による IL-4 の放出', 'Th2 による IL-4 の放出', '. 抗原によるマスト細胞の IgE 架橋'],
                    answerImg: [allergyIgE],
                    answer: 'Th2 による IL-4 の放出',
                    commentary: 'アナフィラキシーショックでは、抗原が認識されるとTh2細胞がIL-4などを放出し、B細胞へのクラススイッチを促し、肥満細胞の表面のFcレセプターに結合した後、抗原が抗体に結合し架橋することによって大量のサイトカインが放出され、ショック状態となる。選択肢のうち４つは誤った内容',
                },
                {
                    detailInfo: '',
                    questionImg: [],
                    questionSentence: 'CD4 ノックアウトマウスにみられるもの',
                    choices: ['IgM 産生できない', '抗体産生細胞とマクロファージ活性化できない', '好中球の殺菌能が低下する'],
                    answerImg: [ThDifferentiation],
                    answer: '抗体産生細胞とマクロファージ活性化できない',
                    commentary: 'IgMを産生するのはB細胞だが、B細胞やマクロファージを活性化しているのはCD4+T細胞である。好中球は自然免疫系でT細胞は関与しない。',
                },
                {
                    detailInfo: '',
                    questionImg: [],
                    questionSentence: 'NK細胞の抑制性受容体について正しいものを１つ',
                    choices: ['NK 細胞の抑制性受容体は細胞内尾部に ITAMをもつ。', 'NK 細胞の抑制性受容体のいくつかは HLA-Cに結合する', 'NK細胞の抑制性受容体のいくつかはインテグリンファミリーである。', 'NK細胞の抑制性受容体のいくつかは TLRファミリーである。', 'NK細胞の抑制性受容体のいくつかは、活性化受容体と同時に発現する。'],
                    answerImg: [NKCell, NKCellReceptor],
                    answer: '2が正しい',
                    commentary: 'ITAM(活性化モチーフ)ではなくITIM。NK細胞にはHLA分子をリガンドとする様々な促進性・抑制性受容体が発現している。',
                },
                {
                    detailInfo: '',
                    questionImg: [],
                    questionSentence: '生殖免疫について誤っているものを 2 つ選びなさい',
                    choices: ['妊娠初期には M1 マクロファージより M2 マクロファージが多い', '脱落膜には制御性T細胞が存在しているため父由来の抗原は攻撃されない', '母児免疫寛容が破綻すると母体の抗原が攻撃される', '脱落膜 NK 細胞のほとんどは CD56 弱陽性 NK 細胞である'],
                    answerImg: [HLATrophoblast, TregTrophoblast, CD56bright],
                    answer: '3と4が誤り',
                    commentary: '妊娠初期のM1マクロファージ（炎症性）とM2マクロファージ（抑制性）は同程度らしい。胎盤脱落膜にはTregが約2倍存在して免疫寛容に寄与している。母児免疫寛容が破綻すると胎児の抗原が母体の免疫システムに攻撃されるが、胎児の免疫機構は成熟していないため逆は起こらない。脱落膜NK細胞の80％はCD56bright NK細胞であり。パーフォリンなどによる細胞障害というよりはサイトカイン産生を主に行う。',
                },
                {
                    detailInfo: '',
                    questionImg: [],
                    questionSentence: '粘膜免疫について誤ってるものを 1つ選べ',
                    choices: ['M細胞は抗原をパイエル板に取り込み樹状細胞に受け渡す', 'リンパ球はビタミンCによってホーミングされる', '腸内フローラには制御性T細胞と Th17細胞のバランスを保つ役割がある'],
                    answerImg: [],
                    answer: '2が誤り',
                    commentary: 'リンパ球はビタミンCではなくビタミンAによってホーミングされる。腸管に存在する樹状細胞は活性化によりビタミンAをレチノイン酸に変換する酵素を発現する。T細胞やB細胞はレチノイン酸に曝露されると、ケモカイン受容体CCR9とインテグリンα4Β7を発現し、それぞれ粘膜固有層の差異静脈内皮細胞が発現するケモカインCCL25と接着分子MadCAMに誘導され、粘膜固有層選択的ホーミングに寄与する。',
                },
                {
                    detailInfo: '',
                    questionImg: [],
                    questionSentence: '食細胞について誤っているものを 2 つ選べ',
                    choices: ['マクロファージは好中球よりも寿命が長い。', '血中の白血球の量は 5000/μL で、血球成分の中で好中球が最も多い。', '左方移動により、未熟な好中球が産生されるが、これはウイルス感染によって引き起こされる。'],
                    answerImg: [],
                    answer: '2と3が誤り',
                    commentary: '血球成分のなかでは赤血球がダントツで多い（およそ400~500万/μL）。細菌感染症で好中球が消費されると、未熟な好中球が末梢血中に確認されることがある（左方移動）が、ウイルス感染では引き起こされない。',
                },
                {
                    detailInfo: '',
                    questionImg: [],
                    questionSentence: 'フローサイトメトリーと免疫化学染色について誤っているもの 2 つ選べ',
                    choices: ['内因性ペルオキシダーゼの不活化にエタノールを用いる。', '内因性ミエロパオキシダーゼはエタノールで除く。', '間接法は直接法より感度が高い。', '酵素抗体染色は光学顕微鏡で観察できる。', 'フローサイトメトリーの前方散乱光と側方散乱光で T 細胞か B 細胞かわかる。', "酵素抗体法は蛍光免疫法に比べ長期間保存できる。"],
                    answerImg: [],
                    answer: '1と5が誤り',
                    commentary: '内因性ペルオキシダーゼは赤血球や顆粒球にみられ、実習の前処理の段階でメタノールや過酸化水素により失活させられている。FSCとSSCではリンパ球・単球・顆粒球の区別が可能だが、それ以降の分別には表面マーカー（T細胞特異的なCD3とB細胞特異的なCD19）に対する蛍光標識抗体による染色が必要。',
                },
                {
                    detailInfo: '',
                    questionImg: [],
                    questionSentence: 'PRRが認識する PAMPsと病原体の組み合わせについて、誤っているものを 2 つ選べ。',
                    choices: ['TLR2ーペプチドグリカンー肺炎球菌', 'TLR4ーリポポリリサッカライドーインフルエンザウイルス', 'TLR9ーDNAー大腸菌', 'CLRーβグルカンーカンジダ', 'NLRー一本鎖 RNAーインフルエンザ菌', "MincleーTDMー結核菌"],
                    answerImg: [TLR, TLRpattern],
                    answer: '2と5が誤り',
                    commentary: 'ウイルスにLPSは無いし、インフルエンザ菌はグラム陰性桿菌なので一本鎖RNAではない。Mincleは結核のPRRとして知られている。',
                },
                {
                    detailInfo: '',
                    questionImg: [],
                    questionSentence: 'HLA について誤っているものを 2 つ選べ',
                    choices: ['HLA はヒトの MHC 遺伝子である。', '赤血球には発現していない。', 'アミノ酸配列が同じであっても、異なる対立遺伝子であることがある。', '片方のアリルの遺伝子が発現すると、もう一方の遺伝子座の発現が抑制される。', 'ハプロタイプとは多形型である。'],
                    answerImg: [MHCVariation, haplotype],
                    answer: '4と5が誤り',
                    commentary: 'HLA:Human Leukocyte Antigenはヒト固有で、多様性に富んだ多数の遺伝子それぞれに多型をもち、それらの組み合わせ→ハプロタイプが父由来母由来両方発現するため、自己と非自己を区別することができる。HLAが異なる場合は臓器移植の際に必ず拒絶反応が起こってしまうが、輸血の際には問題とならない（赤血球には発現しない）',
                },
                {
                    detailInfo: '',
                    questionImg: [],
                    questionSentence: '胸腺での T細胞について誤っているものを 2 つ選べ',
                    choices: ['胸腺において未熟なT細胞は、分化の過程で皮質から髄質へと移行する。', 'TCRα鎖遺伝子再構成は、β鎖再構成に先行して起こる。', '正の選択とは、自己抗原と適度に反応するT細胞を残すことである。', '正の選択はCD4+CD8+T細胞の段階で起こる。', '負の選択は胸腺皮質、正の選択は胸腺髄質で行われる'],
                    answerImg: [TcellDifferentiation, TcellEducation],
                    answer: '2と5が誤り',
                    commentary: 'まずTCRの遺伝子再構成がβ鎖→α鎖の順に行われ、その後再構成されたTCRについてセレクションが行われる。発現胸腺皮質で正の選択（自己抗原と適度な親和性があるTCRを有するT細胞を選別）した後、胸腺髄質で負の選択（自己抗原と強く反応するT細胞を排除）し、成熟T細胞となる。正の選択はDPT細胞(Double Positive)、負の選択はSPT細胞(Single Positive)の段階で行われる。',
                },
                // {
                //     detailInfo: '',
                //     questionImg: [],
                //     questionSentence: '',
                //     choices: ['', '', '', '', ''],
                //     answerImg: [],
                //     answer: '',
                //     commentary: '',
                // },
                // {
                //     detailInfo: '',
                //     questionImg: [],
                //     questionSentence: '',
                //     choices: ['', '', '', '', ''],
                //     answerImg: [],
                //     answer: '',
                //     commentary: '',
                // },
                // {
                //   detailInfo: '',
                //   questionImg: [],
                //   questionSentence: '',
                //   choices: ['', '', '', '', ''],
                //   answerImg: [],
                //   answer: '',
                //   commentary: '',
                // },
            ]
        },
        {
            groupTag: '授業中',
            groupContents: [{
                    detailInfo: '4/07 N県立医科大学後期入試問題（生物）',
                    questionImg: [],
                    questionSentence: '免疫は大きく、自然免疫と獲得免疫（適応免疫）に分けられる。自然免疫に関わる細胞には、組織中にとどまっている（ 1 ）、があり、主に食作用により微生物を処理する。獲得免疫を担う細胞免疫には、（ 2 ）や（ 3 ）があり、あわせて（ 4 ）という。(2)は主に、（ 5 ）から抗原提示を受けてインターロイキンなどの刺激物質を分泌することで（3）に働きかけ、抗体を分泌する（ 6 ）に分化させる。（2）にはウイルス感染細胞を直接攻撃し破壊するものもいる。獲得免疫のうち、抗体が関与する免疫を（ 7 ）免疫といい、（2）が直接標的細胞を殺すことを（ 8 ）免疫という。',
                    answerImg: [],
                    answer: '1.マクロファージ　2.T細胞　3.B細胞　4.リンパ球　5.樹状細胞　6.形質細胞　7.体液性　8.細胞性　',
                    commentary: '',
                },
                {
                    detailInfo: '4/07',
                    questionImg: [],
                    questionSentence: '白血球の正常値は？',
                    choices: ['5/μL', '50/μL', '500/μL', '5000/μL', '50000/μL'],
                    answerImg: [],
                    answer: '5000/μL',
                    commentary: '正常値は4000~9000個/μL,3000は少なく、10000は多いイメージ',
                },
                {
                    detailInfo: '4/07',
                    questionImg: [],
                    questionSentence: '体重65kgの人間の体内には、白血球はどのくらいの数存在しているか？（白血球の正常値は5000個/μL）',
                    answerImg: [],
                    answer: '250億個',
                    commentary: '5000 * 1000000(μL→L) * 5(5Lの血液)',
                },
                {
                    detailInfo: '4/07　出席確認',
                    questionImg: [],
                    questionSentence: '炎症の5徴として正しいのはどちらか',
                    choices: ['浮腫', '腫脹'],
                    answerImg: [],
                    answer: '腫脹',
                    commentary: '漢字間違いが多い。5徴はほかに熱感heat・発赤redness・疼痛swelling・機能障害dysfunction',
                },
                {
                    detailInfo: '4/14　小テスト',
                    questionImg: [],
                    questionSentence: 'サイトカインの特徴として正しいのはどちらか',
                    choices: ['低分子', '高分子'],
                    answerImg: [],
                    answer: '低分子',
                    commentary: 'サイトカインは低分子（分子量三万前後）の糖たんぱく質(glycoprotein)であり、多くは糖鎖を持つ。きわめて微量で効果を発揮する。',
                },
                {
                    detailInfo: '4/14　小テスト',
                    questionImg: [],
                    questionSentence: 'サイトカインの主なシグナル伝達経路として正しいのはどちらか',
                    choices: ['JAK/STAT', 'Notch'],
                    answerImg: [],
                    answer: 'JAK/STAT',
                    commentary: 'ほとんどのサイトカイン受容体はⅠ型・Ⅱ型受容体を介して信号を伝達する。これらはJAK/STAT経路によって標的遺伝子の転写を誘導する。JAKファミリーは4種類、STATは7種類存在する。',
                },
                {
                    detailInfo: '4/14　小テスト',
                    questionImg: [],
                    questionSentence: '抑制性サイトカインとして正しいのはどちらか',
                    choices: ['IL-6', 'IL-10'],
                    answerImg: [],
                    answer: 'IL-10',
                    commentary: '抑制性サイトカインIL-10は、Th2細胞から産生されるTh1抑制因子（その他免疫寛容IgAにも関与する）として同定された。抑制性サイトカインは他にTGF-β（活性化マクロファージや制御性T細胞などが産生する）しか存在しない。炎症性のサイトカインとしてIL-1、TNF、IL-6が挙げられる。',
                },
                {
                    detailInfo: '4/14　小テスト',
                    questionImg: [],
                    questionSentence: '抗原提示能が高いのはどちらか',
                    choices: ['マクロファージ', '樹状細胞'],
                    answerImg: [],
                    answer: '樹状細胞',
                    commentary: '抗原提示細胞として樹状細胞・マクロファージ・B細胞の3つが存在し、自然免疫と獲得免疫の架け橋を担っているが、その中で最も抗原提示能が高いのは樹状細胞。マクロファージは貪食能（大食細胞とよばれる）・殺菌能が高い。',
                },
                {
                    detailInfo: '4/14　小テスト',
                    questionImg: [],
                    questionSentence: 'Pattern Recognition Receptor（パターン認識受容体）として正しいのはどちらか',
                    choices: ['ACE2 Receptor', 'Toll-like Receptor'],
                    answerImg: [TLR],
                    answer: 'TLR/Toll-like Receptor',
                    commentary: 'TLRは最も有名なPRRで、PRRの代表格である。',
                },
                {
                    detailInfo: '4/14　小テスト',
                    questionImg: [],
                    questionSentence: '抗ウイルス作用が高いサイトカインとして正しいのはどちらか',
                    choices: ['IFN-α', 'IFN-γ'],
                    answerImg: [],
                    answer: 'IFN-α',
                    commentary: 'Ⅰ型IFNで、細胞を抗ウイルス状態にする。',
                },
                {
                    detailInfo: '4/14　小テスト',
                    questionImg: [],
                    questionSentence: 'ケモカインの定義として正しいのはどちらか',
                    choices: [
                        '白血球遊走に関わるサイトカイン',
                        '白血球活性化に関わるサイトカイン',
                    ],
                    answerImg: [],
                    answer: '白血球遊走に関わるサイトカイン',
                    commentary: 'chemotactic(走化性) + cytokine（サイトカイン）ケモカインは後にIL-8として命名される。',
                },
                {
                    detailInfo: '4/14　小テスト',
                    questionImg: [],
                    questionSentence: 'Th1細胞が産生するサイトカインとして正しいのはどちらか',
                    choices: ['IL-12', 'IFN-γ'],
                    answerImg: [],
                    answer: 'IFN-γ',
                    commentary: 'ヘルパーT細胞の分化を決定する最も重要な因子はサイトカイン環境。Th0(naive T cell)→Th1...IFN-γを産生し細菌・ウイルスを標的とするヘルパーT細胞への分化にはIL-12が必要。よって、Th1が産生するサイトカインはIFN-γ。他にもTh-4...IL-4などを産生し寄生虫を標的とするヘルパーT細胞への分化にはIL-4が必要で、ヘルパーT細胞の分化誘導にはサイトカインが深くかかわっている。',
                },
                {
                    detailInfo: '4/14　小テスト',
                    questionImg: [],
                    questionSentence: '血球とサイトカインの組み合わせで正しいのはどちらか',
                    choices: ['赤血球-エリスロポエチン', '好中球-トロンボポエチン'],
                    answerImg: [],
                    answer: '赤血球-エリスロポエチン',
                    commentary: 'エリスロポエチンは腎臓から産生され赤血球への分化に造血系サイトカイン。トロンボポエチンは肝臓由来の血小板への分化に必要な造血系サイトカイン。G-CSF(Granulocyte colony-stimulating factor)は骨髄の間質形細胞・血管内皮細胞などが産生し好中球への分化に必要な造血系サイトカイン。',
                },
                {
                    detailInfo: '4/14　小テスト',
                    questionImg: [],
                    questionSentence: '誤っているサイトカイン-微生物の組み合わせを2つ選べ。',
                    choices: [
                        'TLR2-肺炎レンサ球菌',
                        'TLR3-緑膿菌',
                        'TLR4-大腸菌',
                        'TLR5-ヘリコバクターピロリ菌',
                        'RIG-I - インフルエンザ菌',
                        'NOD1-リステリア菌',
                    ],
                    answer: 'TLR3、RIG-I',
                    answerImg: [TLRpattern],
                    commentary: 'ヘリコバクターピロリ菌は鞭毛がある→フラジェリンと結合するので、TLR5の選択肢は正しい。インフルエンザはウイルスなので、RIG-Iとの組み合わせは当たっているが、インフルエンザ菌ではない。その他、大腸菌はグラム陰性菌でTLR4、肺炎連鎖球菌はグラム陽性菌でTLR2。',
                },
                {
                    detailInfo: '4/14',
                    questionImg: [],
                    questionSentence: '血球とサイトカインの組み合わせで正しいのはどれか。3つ選べ',
                    choices: [
                        '好中球-G-CSF',
                        '好酸球-IFNα',
                        'Tリンパ球-IL-2',
                        '赤血球-エリスロポエチン',
                        '血小板-IL-4',
                    ],
                    answer: '好中球、Tリンパ球、赤血球',
                    commentary: '好酸球へはIL-5で分化が誘導される。エリスロポエチンは腎臓で産生される。',
                },
                {
                    detailInfo: '4/21特別講義',
                    questionImg: [],
                    questionSentence: '炎症の５主徴として誤っているものはどれか？（資料8枚目）',
                    answerImg: [],
                    choices: ['Redness', 'Swelling', 'Edema', 'Pain', 'Dysfunction'],
                    answer: 'Edema',
                    commentary: '浮腫Edemaではなく腫脹swelling',
                },
                {
                    detailInfo: '4/21特別講義',
                    questionImg: [],
                    questionSentence: 'がんの10年生存率として最も適切なのはどれか？（資料80枚目）            ',
                    answerImg: [],
                    choices: ['約10%', '約20%', '約40%', '約60%', '約80%'],
                    answer: '約60%',
                    commentary: '5年生存率・10年生存率は前立腺がんなら90%以上、乳がんでも80%以上',
                },
                {
                    detailInfo: '4/28　小テスト',
                    questionImg: [],
                    questionSentence: '小胞体内でインバリアント鎖が結合しているのは次のどちらか？    ',
                    answerImg: [invariantChain],
                    choices: ['MHCクラスI分子', 'MHCクラスII分子'],
                    answer: 'MHCクラスII分子',
                    commentary: '',
                },
                {
                    detailInfo: '4/28　小テスト',
                    questionImg: [],
                    questionSentence: 'クロスプレゼンテーションによる抗原提示が行われるのはどちらか            ',
                    answerImg: [crossPresentation],
                    choices: [
                        '外来性抗原をCD8T細胞に提示する',
                        '内在性抗原をCD8T細胞に提示する',
                    ],
                    answer: '外来性抗原をCD8T細胞に提示する',
                    commentary: 'その他、パターン認識レセプターによる外来性抗原の取り込みも、断片化されればCD8陽性T細胞に抗原提示することができる',
                },
                {
                    detailInfo: '4/28　小テスト',
                    questionImg: [],
                    questionSentence: '脂質抗原を提示するのは次のどちらでしょうか',
                    answerImg: [],
                    choices: ['CD1d', 'MICA'],
                    answer: 'CD1d',
                    commentary: 'テスト本番でもMHC Class1C　ではなく、CD1dまたはMICAとして解答してほしい',
                },
                {
                    detailInfo: '5/12 出席確認',
                    questionImg: [],
                    questionSentence: '日本で初めてノーベル医学・生理学賞を受賞したのは誰か？',
                    answerImg: [],
                    answer: '利根川進',
                    commentary: '',
                },
                {
                    detailInfo: '5/12 出席確認',
                    questionImg: [],
                    questionSentence: '抗体のクラスと機能の組み合わせとして誤っているものを選べ',
                    answerImg: [],
                    choices: ["IgM：補体活性化", "IgM：オプソニン化", "IgA：粘膜面での中和", "IgG：血清中での中和", "IgG：抗体依存性細胞障害活性", "IgE：アレルギー反応"],
                    answer: 'IgM：オプソニン化',
                    commentary: '誤っているというよりは最適ではないもの。オプソニン化はIgGの役割のほうが大きい。',
                },
                {
                    detailInfo: '5/12 出席確認',
                    questionImg: [],
                    questionSentence: '【正誤問題】抗体の多様性はIgGの転写産物のスプライシングによって生み出される',
                    answerImg: [],
                    answer: '誤り',
                    commentary: '参考:VDJリコンビネーション、遺伝子再構成',
                },
                {
                    detailInfo: '5/12 出席確認',
                    questionImg: [],
                    questionSentence: '【正誤問題】一つのB細胞は、2本の染色体に由来する２種類の抗体分子を発現する',
                    answerImg: [],
                    answer: '誤り',
                    commentary: '1つのB細胞に対して1種類の抗体の原則。遺伝子再構成に成功すると対立遺伝子からの発現は抑制される。',
                },
                {
                    detailInfo: '0519レジュメ中',
                    questionImg: [],
                    questionSentence: '胸腺におけるT細胞分化について誤っているものを2つ選べ。',
                    choices: ["負の選択とは自己抗原と過剰に反応するT細胞を排除することである",
                        "正の選択とは自己抗原と適度に反応するT細胞を残すことである",
                        "負の選択は胸腺皮質、正の選択は胸腺髄質でおこる",
                        "核内蛋白AIRE(autoimmune regulator)は種々の自己抗原を産生し、負の選択に寄与する",
                        "CD8+T細胞はCD4+CD8+T細胞 → CD4-CD8-T細胞 → CD8+T細胞の経過をたどり分化する ",
                        "T細胞の遺伝子再構成はCD4-CD8-T細胞の段階から行われる"
                    ],
                    answerImg: [TcellDifferentiation, TcellEducation],
                    answer: '3と5は誤り...正の選択は胸腺皮質、負の選択は胸腺髄質で行われる。CD4-CD8-(Double Negative)T細胞 → CD4+CD8+(Double Positive)T細胞 の順番',
                    commentary: '特にβ鎖はDouble Negativeの段階から行われる。',
                },
                {
                    detailInfo: '0519レジュメ中',
                    questionImg: [],
                    questionSentence: 'T細胞の活性化について誤っているものを2つ選べ。',
                    choices: ["ナイーブT細胞の活性化にはTCRからの活性化シグナルだけでは不十分であり、CD28を介した共刺激が必要である", "TCRシグナルの活性化はITAMのアセチル化によって開始される", "シクロスポリンはカルシニューリンを阻害することで、T細胞の活性化を抑制する",
                        "活性化したCD4+T細胞はIL-2を産生し、T細胞の増殖とヘルパーT細胞への分化を促す",
                        "スーパー抗原はTCRとCD28に同時に結合することで、特定のクローンの著しい活性化と増殖を引き起こす",
                        "Toxic shock syndrome(TSS)は黄色ブドウ球菌由来のスーパー抗原が原因の疾患である"
                    ],
                    answerImg: [TcellActivationSignal, superantigen],
                    answer: '2と5は誤り...TCRシグナルの活性化はFyn&LckやZAP-70のチロシン部分のリン酸化が出発点。スーパー抗原はTCRを非特異的に活性化させ、CD28は関係しない。',
                    commentary: '',
                },
                {
                    detailInfo: '0519レジュメ中',
                    questionImg: [],
                    questionSentence: 'レジュメ中のEnglish Journal of Medicineの動画を見て、次の中から正しいものを選べ',
                    choices: ["トシリズマブはIL-6に対する抗体である",
                        "トシリズマブとプラセボは同数の患者に投与された",
                        "投与された患者は全て入院患者である",
                        "トシリズマブは生存率を優位に改善させた",
                        "トシリズマブ投与群の方が有害事象が高かった"
                    ],
                    answerImg: [],
                    answer: '投与された患者は全て入院患者である',
                    commentary: 'トシリズマブTocillizumabはIL-6受容体に対する抗体で、トシリズマブ：プラセボ群は2:1の割合。トシリズマブはMortality=死亡率には全く影響を与えなかったが、重症化には数％効果があった。',
                },
                {
                    detailInfo: '0519レジュメ中',
                    questionImg: [],
                    questionSentence: 'T細胞の活性化について誤っているものを2つ選べ。',
                    choices: ["T細胞抗原受容体(TCR)α鎖/β鎖はITAM(免疫受容体チロシン活性化モチーフ)を持たないため、シグナル伝達にはCD3との会合が必要である",
                        "ナイーブT細胞はTCRシグナルのみでは活性化できずanergyを誘導する",
                        "活性化T細胞の増殖にはIL-2が必要である",
                        "Th17細胞は寄生虫感染に対する生体防御に重要である",
                        "細胞障害性T細胞から分泌されるGranzyme BはCaspaseの活性化を介して標的細胞にアポトーシスを誘導する",
                        "セントラルメモリーT細胞は、炎症が起こった臓器内で長期間生存する"
                    ],
                    answerImg: [ThDifferentiation, centralMemoryT],
                    answer: '4と6が誤り...寄生虫感染に対応するのはTh2。セントラルメモリーT(TCM)細胞は主に二次リンパ組織のT細胞領域に存在している。',
                    commentary: '',
                },

                {
                    detailInfo: '5/19小テスト(T細胞)',
                    questionImg: [],
                    questionSentence: 'T細胞が分化する臓器はどちらか？',
                    answerImg: [],
                    choices: ["骨髄", "胸腺"],
                    answer: '胸腺(Thymus)',
                    commentary: '',
                },
                {
                    detailInfo: '5/19小テスト(T細胞)',
                    questionImg: [],
                    questionSentence: 'T細胞の教育はどちらが先に行われるか？',
                    answerImg: [],
                    choices: ["正の選択", "負の選択"],
                    answer: '正の選択',
                    commentary: '皮質上皮細胞cTECによって正の選択が行われた後、髄質表皮細胞mTECによって負の選択が行われる。',
                },
                {
                    detailInfo: '5/19小テスト(T細胞)',
                    questionImg: [],
                    questionSentence: 'T細胞抗原受容体（TCR）の構成として多いのはどちらか？  ',
                    choices: ["αβ鎖", "γδ鎖"],
                    answerImg: [],
                    answer: 'αβ鎖',
                    commentary: 'αβ鎖が90%。一般的にT細胞とよぶときはαβ型T細胞',
                },
                {
                    detailInfo: '5/19小テスト(T細胞)',
                    questionImg: [],
                    questionSentence: 'アネルギー（Anergy）の定義として、正しいのはどちらか？  ',
                    choices: ["抗原が与えられても抗原抗体反応が起こらない状態", "抗原が与えられても抗原抗体反応が過剰に起こる状態"],
                    answerImg: [],
                    answer: '抗原が与えられても抗原抗体反応が起こらない状態',
                    commentary: '副刺激がなければ、T細胞は活性化されない。',
                },
                {
                    detailInfo: '5/19小テスト(T細胞)',
                    questionImg: [],
                    questionSentence: 'T細胞の活性化に必須な酵素はどちらか？   ',
                    choices: ["チロシンキナーゼ", "ヒスチジンキナーゼ"],
                    answerImg: [],
                    answer: 'チロシンキナーゼ',
                    commentary: 'T細胞の活性化は、チロシン部分のリン酸化から開始される。',
                },
                {
                    detailInfo: '5/19小テスト(T細胞)',
                    questionImg: [],
                    questionSentence: 'T細胞の増殖・活性化に働くサイトカインはどちらか？   ',
                    choices: ["IL-1", "IL-2"],
                    answerImg: [ThDifferentiation],
                    answer: 'IL-2',
                    commentary: 'T細胞の分化に関わるサイトカインとは別',
                },
                {
                    detailInfo: '5/19小テスト(T細胞)',
                    questionImg: [],
                    questionSentence: '肉芽腫形成に関わるマクロファージはどちらか？   ',
                    choices: ["ランゲルハンス細胞", "類上皮細胞"],
                    answerImg: [],
                    answer: '類上皮細胞',
                    commentary: 'マクロファージは肉芽腫の中でラングハンス巨細胞や類上皮細胞として認められる。',
                },
                {
                    detailInfo: '5/19小テスト(T細胞)',
                    questionImg: [],
                    questionSentence: '先進国におけるアレルギー増加の原因を説明した仮説はどちらか？  ',
                    choices: ["衛生仮説", "抗原仮説"],
                    answerImg: [],
                    answer: '衛生仮説',
                    commentary: '抗原仮説という言葉は存在しない。',
                },
                {
                    detailInfo: '5/19小テスト(T細胞)',
                    questionImg: [],
                    questionSentence: '制御性T細胞に特異的な転写因子はどちらか？ ',
                    choices: ["Foxp3", "T-bet"],
                    answerImg: [],
                    answer: 'Foxp3',
                    commentary: '制御性T細胞：Tregは免疫を抑制する作用を持っていて、分化に必要なFoxp3遺伝子に変異があると自己免疫疾患IPEXを引き起こす',
                },
                {
                    detailInfo: '5/26出席確認',
                    questionImg: [],
                    questionSentence: '補体反応で最も早く活性化されるのは？',
                    choices: ["古典経路", "代替経路", "レクチン経路"],
                    answerImg: [],
                    answer: '代替経路',
                    commentary: '代替経路:Alternative Pathwayは基本的に常時体の中で活性化されている。',
                },
                {
                    detailInfo: '5/26出席確認',
                    questionImg: [],
                    questionSentence: '古典経路のC5転換酵素は？',
                    answerImg: [complementPathway],
                    choices: ["C3bBb3b", "C4b2a3b"],
                    answer: 'C4b2a3b',
                    commentary: '古典経路・レクチン経路で、C5転換酵素として作用する。C3,C4,C5は分解されるとaが遊離されるが、C2はC2bが遊離する。C3bBb3bは代替経路のC5転換酵素。',
                },
                {
                    detailInfo: '5/26出席確認',
                    questionImg: [],
                    questionSentence: '胎盤脱落膜に多いリンパ球はどれか',
                    choices: ["NK細胞", "T細胞", "B細胞"],
                    answerImg: [NKCell],
                    answer: 'NK細胞',
                    commentary: '',
                },
                {
                    detailInfo: '5/26出席確認',
                    questionImg: [],
                    questionSentence: '胎盤トロホブラストに発現していないHLAクラスＩ分子はどれか ',
                    choices: ["HLA-G", "HLA-A", "HLA-C"],
                    answerImg: [HLATrophoblast],
                    answer: 'HLA-A',
                    commentary: '発現して「いない」。HLA-CやHLA-Gは胎盤トロホブラストで発現して、胎児の免疫学的拒絶の抑制作用に寄与している。胎盤では免疫学的寛容のため、比較的多様性の少ないHLA分子（HLA-E,F,G）を発現していて、胎盤脱落膜に多いNK細胞による攻撃を防いでいる。',
                },
                {
                    detailInfo: '6/09 出席確認',
                    questionImg: [],
                    questionSentence: '胎盤通過能をもつアイソタイプは？',
                    choices: ["IgA", "IgD", "IgE", "IgG", "IgM"],
                    answerImg: [],
                    answer: 'IgG',
                    commentary: 'FcRnによってトランスサイトーシスされ、胎児血中に母体由来IgGが分布する。母体由来IgGは生後6ヶ月程度で消える→この時期の感染には気を付ける',
                },
                {
                    detailInfo: '6/09 出席確認',
                    questionImg: [],
                    questionSentence: '補体活性化能が最も高いアイソタイプは？',
                    choices: ["IgA", "IgD", "IgE", "IgG", "IgM"],
                    answerImg: [],
                    answer: 'IgM',
                    commentary: 'IgGもサブクラスによっては補体活性化能力があるが、IgMが最も高い。',
                },
                {
                    detailInfo: '6/09 出席確認２',
                    questionImg: [],
                    questionSentence: '免疫学的に1と2のどちらのワクチンが効果が高いと考えられるか？',
                    choices: ["成人用23価の莢膜多糖を配合したワクチン(PPSV23)", "胎児用7価の莢膜多糖+ジフテリアタンパクを配合したワクチン(PCV7)"],
                    answerImg: [],
                    answer: '2',
                    commentary: '2は莢膜多糖にタンパク質(アジュバンド/TD抗原)を含んでいるため、T細胞が関与した免疫を活性化することで高い親和性を持つ抗原を産生し免疫記憶が持続しやすい。1は莢膜多糖のみなのでTI抗原。',
                },
                {
                    detailInfo: '6/09 出席確認3',
                    questionImg: [],
                    questionSentence: '虫垂炎の際に増加する白血球は主にどれか？',
                    choices: ["Neutrocyte", "Lymphocyte", "Monocyte"],
                    answerImg: [],
                    answer: 'Neutrocyte？',
                    commentary: '',
                },
                {
                    detailInfo: '9/08 小テスト',
                    questionImg: [question09081],
                    questionSentence: '血清の等電点電気泳動像である。抗体活性があるのはA~Eのどれか',
                    //    choices:["","","","",""],
                    answerImg: [],
                    answer: 'E',
                    commentary: 'Eが抗体（γグロブリン）。Aはアルブミン',
                },
                {
                    detailInfo: '9/08 小テスト',
                    questionImg: [],
                    questionSentence: '抗体反応の検出に二次抗体を必要とするのは？',
                    choices: ["直接法", "間接法"],
                    answerImg: [],
                    answer: '間接法',
                    commentary: '直接法は一次抗体に直に蛍光物質が結合している。間接法はノイズが多いが、感度が高く（反応を増幅することができる）、頻用されている。',
                },
                {
                    detailInfo: '9/08 小テスト',
                    questionImg: [],
                    questionSentence: '血清中のスギ花粉に対するIgE濃度をELISA法で測定したい。下記の内、必要のない試薬はどれか。',
                    choices: ["抗原（スギ花粉由来）", "患者血清", "HRP標識抗ヒトIgG抗体", "HRP標識抗ヒトIgE交代"],
                    answerImg: [],
                    answer: 'HRP標識抗ヒトIgG抗体',
                    commentary: '',
                },
                {
                    detailInfo: '9/08 小テスト',
                    questionImg: [],
                    questionSentence: '血清中のスギ花粉の抗体価を高感度で測定したい。あなたなら、どの測定方法を選択するか。',
                    choices: ["サンドイッチELISA法", "化学発光酵素免疫測定法（CLEIA)", "放射性免疫測定法　(RIA)"],
                    answerImg: [],
                    answer: 'どれも正解',
                    commentary: '何としても見たい場合は放射線、程よくみたい場合はCLEIA、比較的手軽に見たい場合はサンドイッチELISA。見たい抗体によって使い分けで、どれも間違いではない。',
                },
                {
                    detailInfo: '9/08 小テスト',
                    questionImg: [],
                    questionSentence: 'A型赤血球が抗A血清で凝集するのはABO血液型判定の何試験？',
                    choices: ["オモテ試験", "ウラ試験"],
                    answerImg: [],
                    answer: 'オモテ試験',
                    commentary: 'A型赤血球を加える試験がオモテ試験、血清を加える試験がウラ試験',
                },
                {
                    detailInfo: '9/08 小テスト',
                    questionImg: [question09082],
                    questionSentence: 'PD-L1の腫瘍組織での発現をDAB発色により免疫染色で解析した。PD-L1が発現している場所は？',
                    answerImg: [],
                    answer: '2番',
                    commentary: 'DAB発色と書いてあるので、茶色く染色されているところが陽性。実習で見たと思います。',
                },
                {
                    detailInfo: '9/08 小テスト',
                    questionImg: [],
                    questionSentence: '末梢血単核球をフローサイトメトリーで解析した。CD4陽性T細胞は①～④のどの画分に見られるか？',
                    answerImg: [],
                    answer: '',
                    commentary: 'CD3とCD4のダブルポジティブの部分が該当する。',
                },
                {
                    detailInfo: '9/08 出席テスト',
                    questionImg: [],
                    questionSentence: '免疫不全で多いのはどちらか',
                    choices: ["原発性", "続発性"],
                    answerImg: [],
                    answer: '続発性',
                    commentary: '続発性：Secondaryの方が圧倒的に多い(>99%)。原発性：Primaryは少ないが、国家試験に出る。私も自分で原発性を診断したことはない。続発性として、糖尿病・免疫抑制剤・アルコール過剰摂取・HIV感染など。免疫不全状態だと重症化しやすい',
                },
                {
                    detailInfo: '9/08 出席テスト',
                    questionImg: [],
                    questionSentence: '国内の新規HIV患者数が多いのはどちらか',
                    choices: ["男性", "女性"],
                    answerImg: [],
                    answer: '男性(日本では新規感染の95%が男性)',
                    commentary: 'HIVとAIDSの違いをわかっておくように。世界的に広く感染しているが、日本でも新規報告が確認されている（世界でも稀な右肩上がりの推移で東京・大阪などの都市部に多い）。日本の場合はMEMの男性に非常に多い。AIDSの診断にはHIVの感染確認だけでなく、AIDS指標疾患（23種類）である感染症・腫瘍の確認が必要。ほとんどの感染症は東京が多くなるが、結核だけは大阪が顕著に多いので注意',
                },
                {
                    detailInfo: '9/08 出席テスト',
                    questionImg: [],
                    questionSentence: '日和見感染症が併発しやすいヘルパーT細胞の数はいくら未満か',
                    choices: ["200/mm^3", "2000/mm^3"],
                    answerImg: [],
                    answer: '200/mm^3',
                    commentary: 'ヘルパーT細胞の数が1マイクロリッターあたり200個を下回ると、普段我々がかかりにくいような疾患にかかりやすくなる。',
                },
                {
                    detailInfo: '9/08 出席テスト',
                    questionImg: [],
                    questionSentence: '原発性免疫不全症候群で多いのはどちらか',
                    choices: ["食細胞異常", "抗体不全"],
                    answerImg: [],
                    answer: '抗体不全',
                    commentary: '原発性免疫不全症候群だけで200種類近くの疾患がある。大きく分けると、複合免疫不全症（）・免疫不全を伴う特徴的な症候群（国家試験に非常に出しやすい）・液性免疫＝抗体免疫不全・免疫調節障害・食細胞機能不全など。日本全国で1300人強患者がおり、その四割が抗体不全症。',
                },
                {
                    detailInfo: '9/08 出席テスト',
                    questionImg: [],
                    questionSentence: '好中球に異常を来たす疾患はどちらか',

                    choices: ["Wiscott-Aldrich症候群", "Chediak-Higashi症候群"],
                    answerImg: [],
                    answer: 'Chediak-Higashi症候群',
                    commentary: 'Chediak-Higashi症候群はLYST遺伝子の異常により、ファゴソームとリソソームの融合に障害がある→特徴的なペルオキシダーゼ陽性巨大顆粒好中球。85%の患者が病気の経過中に突然病状悪化する「急性転化」も試験に頻出。　Wiskott-Aldrich症候群は３主徴(血小板減少・湿疹・易感染性が特徴的で試験に出しやすい。WASProteinの遺伝子異常が根本的原因。',
                },
                {
                    detailInfo: '9/08 出席テスト',
                    questionImg: [],
                    questionSentence: '下記の免疫不全症のうち、より重症なのはどちらか',
                    choices: ["SCID", "X連鎖無ガンマグロブリン血症"],
                    answerImg: [],
                    answer: 'SCID',
                    commentary: '一番免疫機構でなくなっては困るのがT細胞。あらゆる疾患にかかりやすくなる。免疫不全になると呼吸器・消化器・皮膚・全身性（深部）に感染症が発生しやすくなり、また腫瘍が取り除かれにくくなる。SCID(Severe Combined Immuno Deficiency)は半数以上がIL-2γ遺伝子に異常がある複合的な免疫不全で免疫不全症の中でも最も重症なタイプ、X連鎖無ガンマグロブリン血症ではB細胞の成熟に関わるBTKに異常があるため抗体が産生されない。両方ともX染色体に関係していて、男児だけが発症する。',
                },
                // {
                //   detailInfo: '9/08 出席テスト',
                //   questionImg: [],
                //   questionSentence:
                //     '',
                //   answerImg: [],
                //   answer: '',
                //   commentary: '',
                // },

            ],
        },
        {
            groupTag: 'レポート課題',
            groupContents: [{
                    detailInfo: '4/14',
                    questionImg: [],
                    questionSentence: '下記の pattern recognition receptor (PRR)のリガンドである pathogen associated molecular pattern (PAMPs)ならびに代表的な病原体を列挙せよ。 (1)TLR2',
                    answerImg: [TLR, TLRpattern],
                    answer: 'PAMPs：ペプチドグリカン・リポタイコ酸。代表的な病原体：グラム陽性菌（肺炎球菌・黄色ブドウ球菌・溶連菌・ジフテリア菌など）',
                    commentary: 'ペプチドグリカン・リポタイコ酸はグラム陽性菌の厚い細胞壁特有の物質。グラム陽性菌には外膜はない。',
                },
                {
                    detailInfo: '4/14',
                    questionImg: [],
                    questionSentence: '下記の pattern recognition receptor (PRR)のリガンドである pathogen associated molecular pattern (PAMPs)ならびに代表的な病原体を列挙せよ。 (2)TLR4',
                    answerImg: [TLR, LPS],
                    answer: 'PAMPs：LSPなど。代表的な病原体：グラム陰性菌（大腸菌・サルモネラ菌・緑膿菌・淋菌など）',
                    commentary: 'LPSはグラム陰性菌の外膜成分。グラム陰性菌は細胞壁が薄い。',
                },
                {
                    detailInfo: '4/14',
                    questionImg: [],
                    questionSentence: '下記の pattern recognition receptor (PRR)のリガンドである pathogen associated molecular pattern (PAMPs)ならびに代表的な病原体を列挙せよ。 (3)RIG-I like receptor',
                    answerImg: [RLR],
                    answer: 'PAMPs：ウイルス由来RNA。代表的な病原体：RNAウイルス（インフルエンザウイルス・コロナウイルス・C型肝炎ウイルスなど）',
                    commentary: 'RLGに受容されることによって、炎症性サイトカインやIFN-β含むⅠ型インターフェロンの分泌が刺激される。',
                },
                {
                    detailInfo: '4/14',
                    questionImg: [],
                    questionSentence: 'サイトカインの定義とその特徴（5つ以上）を述べよ',
                    answerImg: [],
                    answer: '【定義】細胞が産生する微量生理活性タンパク質の総称。【特徴】1.多くは低分子糖たんぱく質である。2.主に産生局所で働く。3.きわめて微量で効果を発揮する。4.細胞表面に発現する特異的な受容体に結合し、効果を発揮する。5.多様な生理活性を持つ。6.異なるサイトカインが同じ活性を示す（重複性）。7.種々のサイトカイン間で相互依存性がある（サイトカインネットワーク）。',
                    commentary: '',
                },
                {
                    detailInfo: '4/14',
                    questionImg: [],
                    questionSentence: '肺の上皮細胞に病原体が侵入してきたと仮定して、病原体を認識してから、リンパ節でT細胞と出会うまでの過程（樹状細胞の動態）を200字以上で述べよ',
                    answerImg: [homing, MHCClass2],
                    answer: '侵入した病原体の刺激に反応して、上皮細胞からCCL20が産生され、CCR6陽性の未熟な樹状細胞がCCL20発現部位に遊走する。DCは抗原を取り込む際にPAMPsを認識して活性化・成熟し、CCR6の発現が低下する一方、CCR7の発現が上昇する。そしてCCR7を発現した成熟DCは、輸入リンパ管を介して、CCL19/CCL21の発現が見られる（所属）リンパ節のT細胞領域に遊走すると同時に、病原体を分解処理し、その結果生じたペプチドをMHC分子の上に提示する。リンパ節に入ると、低い確率だが抗原提示細胞上のMHC+ペプチド複合体と強く相互作用することのできる抗原特異的なT細胞と出会い、抗原提示を行う。',
                    commentary: 'CCL20は肺・肝臓などの組織に特異的で、CCL19/21はリンパ節T細胞領域（のHEV）に部位特異的。CCR6は未熟樹状細胞やTh17に発現していて、CCR7は成熟樹状細胞・ナイーブT細胞に特異的であるため、このような複雑な機構が成り立つ。',
                },
                {
                    detailInfo: '',
                    questionImg: [],
                    questionSentence: 'Th1細胞の分化誘導に必要なサイトカインとその分化した各ヘルパーT 細胞が産生するサイトカインを記せ。',
                    answerImg: [ThDifferentiation],
                    answer: '【分化に必要なサイトカイン】IL-12　【産生するサイトカイン】IFN-γ',
                    commentary: 'IFN-γはⅡ型インターフェロンで、結核診断(ツベルクリン検査)に用いられる',
                },
                {
                    detailInfo: '',
                    questionImg: [],
                    questionSentence: 'Th2細胞の分化誘導に必要なサイトカインとその分化した各ヘルパーT 細胞が産生するサイトカインを記せ。',
                    answerImg: [ThDifferentiation],
                    answer: '【分化に必要なサイトカイン】IL-4　【産生するサイトカイン】IL-4/IL-5/IL-13',
                    commentary: '',
                },
                {
                    detailInfo: '',
                    questionImg: [],
                    questionSentence: 'Th17細胞の分化誘導に必要なサイトカインとその分化した各ヘルパーT 細胞が産生するサイトカインを記せ。',
                    answerImg: [ThDifferentiation, TGFBeta],
                    answer: '【分化に必要なサイトカイン】IL-6＋TGF-β 【産生に必要なサイトカイン】 IL-17',
                    commentary: 'IL-6は炎症性サイトカインで、TGF-βは抑制性サイトカイン。Th17は過剰な炎症反応を抑制するヘルパーT細胞。',
                },
                // {
                //     detailInfo: '',
                //     questionImg: [],
                //     questionSentence: '',
                //     answerImg: [],
                //     answer: '',
                //     commentary: '',
                //   },
                {
                    detailInfo: '5/19',
                    questionImg: [],
                    questionSentence: '胸腺でのT細胞の分化過程について、なぜ正の選択と負の選択が必要なのか述べよ',
                    answerImg: [TcellEducation],
                    commentary: 'T細胞は抗原提示を受けるためにMHC分子（と抗原の複合体）と結合できなければならず、また自己抗原に反応してはいけない。',
                    answer: '正の選択は適度に「自己」と反応できるような T 細胞を選ぶ過程を意味する。 これは自己抗原と全く反応できない T細胞を排除するために必要である。 一 方、負の選択は自己に強く反応するような T細胞を取り除く過程を意味する。 これは自分の体の細胞(自己抗原)を攻撃する T細胞を排除するために必要である。',
                },
                {
                    detailInfo: '5/19',
                    questionImg: [],
                    questionSentence: 'αβT細胞とγδT細胞との違いについて述べよ。',
                    answerImg: [TcellGammaDelta, TCRSegments],
                    answer: '全身に分布する通常の αβT細胞とは違い、γδT細胞はリンパ球ストレス(細胞傷害)監視機構(lymphoid stress-surveillance)と呼ばれる生体防御反応を担う中 心的な細胞である。皮膚や粘膜に局在してみられ、MHC 拘束性の抗原提示は受けず、自然免疫を担っている。さらにさらにストレス暴露により細胞に誘導される多様な分子を迅速に認識する必要があるため、TCR 以外にも NKG2D や TLR などの多彩な受容体を発現している。また胸腺内でダブルネガティブ(DN) の段階で、αβT細胞が発生するより先に、γδT細胞は TCR 遺伝子の再配列を受ける一方、一部のγδT細胞には胸腺外分化するものもある。',
                    commentary: 'T細胞抗原受容体にはαβ型（90%）とγδ型(10%)があり、γδT細胞はリンパ球ストレス（細胞障害）監視機構と呼ばれる生体防御反応担う中心的な細胞である。細菌感染やウイルス感染などの外からのストレスに加えて、がん化に伴う細胞の変化に対しても敏感に感知することが可能。',
                },
                {
                    detailInfo: '5/19',
                    questionImg: [],
                    questionSentence: 'Tregの抑制的制御のメカニズムを述べよ。',
                    answerImg: [Treg, TGFBeta],
                    answer: 'Treg の発現する CTLA-4 は、抗原提示細胞において CD80/CD86 の発現を低く抑えることにより、他の T細胞の活性化に必要な副刺激を提供できないようにしている。また、Treg は高親和性の IL-2 受容体 (CD25) を高発現し、周囲から IL-2を受け取ることにより、ほかの T細胞から IL-2 を奪い取り、その活性化を妨げる。さらに抑制性サイトカインである IL-10 や TGF-βを産生することで、 T 細胞の活性化を妨げる。',
                    commentary: '1.抗原提示細胞のCD80/CD86の発現を低く抑える。2.高親和性のIL-2受容体によってほかのT細胞からIL-2を奪って活性化を妨げる',
                },
                // {
                //   detailInfo: '',
                //   questionImg: [],
                //   questionSentence: '',
                //   answerImg: [],
                //   answer: '',
                //   commentary: '',
                // },
            ],
        },
    ])
    const showQuestionList = () => {
        return questionList
    }
    return {
        showQuestionList,
        appName,
        jpName,
    }
}